/*
Script created by SQL Compare from Red Gate Software Ltd at 10/06/2017 4:29:18 PM
Run this script on PC01\SQL2008.ECUS5_CANG_PH to make it the same as PC01\SQL2008.ECUS5_CANG_DEV
Please back up your database before running this script
*/
SET NUMERIC_ROUNDABORT OFF
GO
SET ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, ARITHABORT, QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
IF EXISTS (SELECT * FROM tempdb..sysobjects WHERE id=OBJECT_ID('tempdb..#tmpErrors')) DROP TABLE #tmpErrors
GO
CREATE TABLE #tmpErrors (Error int)
GO
SET XACT_ABORT ON
GO
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
GO
BEGIN TRANSACTION
GO
PRINT N'Creating [dbo].[HL_KB_XUAT_CT]'
GO
CREATE TABLE [dbo].[HL_KB_XUAT_CT]
(
[HL_KB_XUAT_CTID] [numeric] (18, 0) NOT NULL IDENTITY(1, 1),
[HL_KB_XUATID] [numeric] (18, 0) NULL,
[HL_KB_NHAP_CTID] [numeric] (18, 0) NULL,
[HL_KB_NHAP_CT_TKID] [numeric] (18, 0) NULL,
[SO_HIEU_PTVT] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SO_CHUYEN] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGAY_TAU_DEN] [datetime] NULL,
[SO_VAN_DON] [nvarchar] (35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DINH_DANH_HANG_HOA] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SO_LUONG] [float] NULL,
[MA_DVT] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GHI_CHU] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MA_HINH_THUC] [int] NULL
)

GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Creating primary key [PK_HL_KB_XUAT_CT] on [dbo].[HL_KB_XUAT_CT]'
GO
ALTER TABLE [dbo].[HL_KB_XUAT_CT] ADD CONSTRAINT [PK_HL_KB_XUAT_CT] PRIMARY KEY CLUSTERED  ([HL_KB_XUAT_CTID])
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Creating [dbo].[HL_VANDON_TRACUU]'
GO
CREATE TABLE [dbo].[HL_VANDON_TRACUU]
(
[HL_VANDON_TRACUUID] [numeric] (18, 0) NOT NULL IDENTITY(1, 1),
[MA_KHO] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[_XORN] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SO_HIEU_PTVT] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SO_CHUYEN] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGAY_TAU_DEN] [datetime] NULL,
[SO_VAN_DON] [nvarchar] (35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DINH_DANH_HANG_HOA] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VI_TRI_HANG] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MO_TA_HANG] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GHI_CHU] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TRANG_THAI] [int] NOT NULL CONSTRAINT [DF_HL_VANDON_TRACUU_TRANG_THAI] DEFAULT ((0)),
[GUID] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SO_TN] [numeric] (18, 0) NULL,
[NGAY_TN] [datetime] NULL,
[MESSAGEID] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGUOI_TAO] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGAY_TAO] [datetime] NULL,
[NGUOI_SUA] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGAY_SUA] [datetime] NULL
)

GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Creating primary key [PK_HL_VANDON_TRACUU] on [dbo].[HL_VANDON_TRACUU]'
GO
ALTER TABLE [dbo].[HL_VANDON_TRACUU] ADD CONSTRAINT [PK_HL_VANDON_TRACUU] PRIMARY KEY CLUSTERED  ([HL_VANDON_TRACUUID] DESC)
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Creating [dbo].[HL_TOKHAI_TRACUU]'
GO
CREATE TABLE [dbo].[HL_TOKHAI_TRACUU]
(
[HL_TOKHAI_TRACUUID] [numeric] (18, 0) NOT NULL IDENTITY(1, 1),
[MA_KHO] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SOTK] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGAY_DK] [datetime] NULL,
[MA_LH] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MA_HQ] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LOAI_TC] [int] NULL,
[MA_HQ_GIAM_SAT] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PHAN_LUONG] [nchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MA_TTTK] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MA_DV] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TEN_DV] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[THOI_GIAN_KET_XUAT] [datetime] NULL,
[NOI_DUNG_PHAN_HOI] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TRANG_THAI] [int] NOT NULL CONSTRAINT [DF_HL_TOKHAI_TRACUU_TRANG_THAI] DEFAULT ((0)),
[GUID] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SO_TN] [bigint] NULL,
[NGAY_TN] [datetime] NULL,
[MESSAGEID] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MESSAGEID_KT] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGUOI_TAO] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGAY_TAO] [datetime] NULL,
[NGUOI_SUA] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGAY_SUA] [datetime] NULL
)

GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Creating primary key [PK_HL_TOKHAI_TRACUU] on [dbo].[HL_TOKHAI_TRACUU]'
GO
ALTER TABLE [dbo].[HL_TOKHAI_TRACUU] ADD CONSTRAINT [PK_HL_TOKHAI_TRACUU] PRIMARY KEY CLUSTERED  ([HL_TOKHAI_TRACUUID])
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Creating [dbo].[HL_KB_HANGHOA_CT]'
GO
CREATE TABLE [dbo].[HL_KB_HANGHOA_CT]
(
[HL_KB_HANGHOA_CTID] [numeric] (18, 0) NOT NULL IDENTITY(1, 1),
[HL_KB_HANGHOAID] [numeric] (18, 0) NULL,
[SO_VAN_DON] [nvarchar] (35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DINH_DANH_HANG_HOA] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SO_LUONG] [float] NULL,
[MA_DVT] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)

GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Creating primary key [PK_HL_KB_HANGHOA_CT] on [dbo].[HL_KB_HANGHOA_CT]'
GO
ALTER TABLE [dbo].[HL_KB_HANGHOA_CT] ADD CONSTRAINT [PK_HL_KB_HANGHOA_CT] PRIMARY KEY CLUSTERED  ([HL_KB_HANGHOA_CTID])
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Creating [dbo].[HL_KB_THAYDOI]'
GO
CREATE TABLE [dbo].[HL_KB_THAYDOI]
(
[HL_KB_THAYDOIID] [numeric] (18, 0) NOT NULL IDENTITY(1, 1),
[MA_KHO] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGAY_KB] [datetime] NULL,
[GHI_CHU] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[_XORN_CU] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[_XORN_MOI] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HL_KB_NHAPID] [numeric] (18, 0) NULL,
[SO_HIEU_PTVT] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SO_CHUYEN] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGAY_TAU_DEN] [datetime] NULL,
[TRANG_THAI] [int] NOT NULL CONSTRAINT [DF_HL_KB_THAYDOI_TRANG_THAI] DEFAULT ((0)),
[SO_TN] [numeric] (18, 0) NULL,
[NGAY_TN] [datetime] NULL,
[MESSAGEID] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GUID] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGUOI_TAO] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGAY_TAO] [datetime] NULL,
[NGUOI_SUA] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGAY_SUA] [datetime] NULL
)

GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Creating primary key [PK_HL_KB_THAYDOI] on [dbo].[HL_KB_THAYDOI]'
GO
ALTER TABLE [dbo].[HL_KB_THAYDOI] ADD CONSTRAINT [PK_HL_KB_THAYDOI] PRIMARY KEY CLUSTERED  ([HL_KB_THAYDOIID])
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Creating [dbo].[HL_VANDON_TRACUU_CT]'
GO
CREATE TABLE [dbo].[HL_VANDON_TRACUU_CT]
(
[HL_VANDON_TRACUU_CTID] [numeric] (18, 0) NOT NULL IDENTITY(1, 1),
[HL_VANDON_TRACUUID] [numeric] (18, 0) NOT NULL,
[SOTK] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGAY_DK] [datetime] NULL,
[MA_LH] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MA_HQ] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MA_HQ_GIAM_SAT] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PHAN_LUONG] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MA_DV] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TEN_DV] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MA_TTTK] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[THOI_GIAN_KET_XUAT] [datetime] NULL,
[SO_LUONG] [float] NULL,
[MA_DVT] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)

GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Creating primary key [PK_HL_VANDON_TRACUU_CT] on [dbo].[HL_VANDON_TRACUU_CT]'
GO
ALTER TABLE [dbo].[HL_VANDON_TRACUU_CT] ADD CONSTRAINT [PK_HL_VANDON_TRACUU_CT] PRIMARY KEY CLUSTERED  ([HL_VANDON_TRACUU_CTID])
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Creating [dbo].[HL_KB_HUY]'
GO
CREATE TABLE [dbo].[HL_KB_HUY]
(
[HL_KB_HUYID] [numeric] (18, 0) NOT NULL IDENTITY(1, 1),
[_XORN] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MA_KHO] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[HL_KB_NHAP_CTID] [numeric] (18, 0) NOT NULL,
[NGAY_KB] [datetime] NULL,
[LY_DO_HUY] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GHI_CHU] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GUID] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SO_TN] [numeric] (18, 0) NULL,
[NGAY_TN] [datetime] NULL,
[MESSAGEID] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TRANG_THAI] [int] NOT NULL CONSTRAINT [DF_HL_KB_HUY_TRANG_THAI] DEFAULT ((0)),
[NGUOI_TAO] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGAY_TAO] [datetime] NULL,
[NGUOI_SUA] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGAY_SUA] [datetime] NULL
)

GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Creating primary key [PK_HL_KB_HUY] on [dbo].[HL_KB_HUY]'
GO
ALTER TABLE [dbo].[HL_KB_HUY] ADD CONSTRAINT [PK_HL_KB_HUY] PRIMARY KEY CLUSTERED  ([HL_KB_HUYID])
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Creating [dbo].[HL_KB_XUAT_141_CT]'
GO
CREATE TABLE [dbo].[HL_KB_XUAT_141_CT]
(
[HL_KB_XUAT_141_CTID] [numeric] (18, 0) NOT NULL IDENTITY(1, 1),
[HL_KB_XUAT_141ID] [numeric] (18, 0) NOT NULL,
[HL_KB_NHAP_CTID] [numeric] (18, 0) NULL,
[SO_HIEU_PTVT] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SO_CHUYEN] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGAY_TAU_DEN] [datetime] NULL,
[SO_VAN_DON] [nvarchar] (35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DINH_DANH_HANG_HOA] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SO_LUONG] [float] NULL,
[MA_DVT] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGAY_RA_KHO] [datetime] NULL,
[MA_HINH_THUC] [int] NULL,
[GHI_CHU] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)

GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Creating primary key [PK_HL_KB_XUAT_141_CT] on [dbo].[HL_KB_XUAT_141_CT]'
GO
ALTER TABLE [dbo].[HL_KB_XUAT_141_CT] ADD CONSTRAINT [PK_HL_KB_XUAT_141_CT] PRIMARY KEY CLUSTERED  ([HL_KB_XUAT_141_CTID])
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Creating [dbo].[HL_KB_XUAT_141]'
GO
CREATE TABLE [dbo].[HL_KB_XUAT_141]
(
[HL_KB_XUAT_141ID] [numeric] (18, 0) NOT NULL IDENTITY(1, 1),
[MA_KHO] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGAY_KB] [datetime] NULL,
[GHI_CHU] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TRANG_THAI] [int] NOT NULL CONSTRAINT [DF_HL_KB_XUAT_141_TRANG_THAI] DEFAULT ((0)),
[SO_TN] [numeric] (18, 0) NULL,
[NGAY_TN] [datetime] NULL,
[MESSAGEID] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GUID] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGUOI_TAO] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGAY_TAO] [datetime] NULL,
[NGUOI_SUA] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGAY_SUA] [datetime] NULL
)

GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Creating primary key [PK_HL_KB_XUAT_141] on [dbo].[HL_KB_XUAT_141]'
GO
ALTER TABLE [dbo].[HL_KB_XUAT_141] ADD CONSTRAINT [PK_HL_KB_XUAT_141] PRIMARY KEY CLUSTERED  ([HL_KB_XUAT_141ID])
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Creating [dbo].[HL_KB_THAYDOI_CT]'
GO
CREATE TABLE [dbo].[HL_KB_THAYDOI_CT]
(
[HL_KB_THAYDOI_CTID] [numeric] (18, 0) NOT NULL IDENTITY(1, 1),
[HL_KB_THAYDOIID] [numeric] (18, 0) NULL,
[HL_KB_NHAP_CTID] [numeric] (18, 0) NULL,
[SO_VAN_DON] [nvarchar] (35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DINH_DANH_HANG_HOA] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GHI_CHU] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)

GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Creating primary key [PK_HL_KB_THAYDOI_CT] on [dbo].[HL_KB_THAYDOI_CT]'
GO
ALTER TABLE [dbo].[HL_KB_THAYDOI_CT] ADD CONSTRAINT [PK_HL_KB_THAYDOI_CT] PRIMARY KEY CLUSTERED  ([HL_KB_THAYDOI_CTID])
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Creating [dbo].[HL_TOKHAI_TRACUU_CT]'
GO
CREATE TABLE [dbo].[HL_TOKHAI_TRACUU_CT]
(
[HL_TOKHAI_TRACUU_CTID] [numeric] (18, 0) NOT NULL IDENTITY(1, 1),
[HL_TOKHAI_TRACUUID] [numeric] (18, 0) NOT NULL,
[SO_HIEU_PTVT] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SO_CHUYEN] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGAY_TAU_DEN] [datetime] NULL,
[SO_VAN_DON] [nvarchar] (35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DINH_DANH_HANG_HOA] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SO_LUONG] [float] NULL,
[MA_DVT] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VI_TRI_HANG] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MO_TA_HANG] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GHI_CHU] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)

GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Creating primary key [PK_HL_TOKHAI_TRACUU_CT] on [dbo].[HL_TOKHAI_TRACUU_CT]'
GO
ALTER TABLE [dbo].[HL_TOKHAI_TRACUU_CT] ADD CONSTRAINT [PK_HL_TOKHAI_TRACUU_CT] PRIMARY KEY CLUSTERED  ([HL_TOKHAI_TRACUU_CTID])
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Creating [dbo].[HL_KB_SAIKHAC_CT]'
GO
CREATE TABLE [dbo].[HL_KB_SAIKHAC_CT]
(
[HL_KB_SAIKHAC_CTID] [numeric] (18, 0) NOT NULL IDENTITY(1, 1),
[HL_KB_SAIKHACID] [numeric] (18, 0) NOT NULL,
[SO_HIEU_PTVT] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SO_CHUYEN] [nvarchar] (35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HO_HIEU_TAU] [nvarchar] (35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SO_IMO] [nvarchar] (35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGAY_TAU_DEN] [datetime] NULL,
[SO_VAN_DON] [nvarchar] (35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DINH_DANH_HANG_HOA] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LOAI_SAI_KHAC] [int] NULL,
[GHI_CHU] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GUID] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)

GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Creating primary key [PK_HL_KB_SAIKHAC_CT] on [dbo].[HL_KB_SAIKHAC_CT]'
GO
ALTER TABLE [dbo].[HL_KB_SAIKHAC_CT] ADD CONSTRAINT [PK_HL_KB_SAIKHAC_CT] PRIMARY KEY CLUSTERED  ([HL_KB_SAIKHAC_CTID])
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Creating [dbo].[HL_KB_NHAP]'
GO
CREATE TABLE [dbo].[HL_KB_NHAP]
(
[HL_KB_NHAPID] [numeric] (18, 0) NOT NULL IDENTITY(1, 1),
[MA_KHO] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[_XORN] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SO_HIEU_PTVT] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SO_CHUYEN] [nvarchar] (35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGAY_TAU_DEN] [datetime] NULL,
[NGAY_KB] [datetime] NULL,
[GHI_CHU] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TONG_SO_KIEN] [int] NULL,
[TRANG_THAI] [int] NOT NULL CONSTRAINT [DF_HL_KB_NHAP_TRANG_THAI] DEFAULT ((0)),
[SO_TN] [numeric] (18, 0) NULL,
[NGAY_TN] [datetime] NULL,
[SO_TN_SUA] [numeric] (18, 0) NULL,
[NGAY_TN_SUA] [datetime] NULL,
[MESSAGEID] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GUID] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGUOI_TAO] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGAY_TAO] [datetime] NULL,
[NGUOI_SUA] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGAY_SUA] [datetime] NULL
)

GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Creating primary key [PK_HL_KB_NHAP] on [dbo].[HL_KB_NHAP]'
GO
ALTER TABLE [dbo].[HL_KB_NHAP] ADD CONSTRAINT [PK_HL_KB_NHAP] PRIMARY KEY CLUSTERED  ([HL_KB_NHAPID])
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Creating [dbo].[HL_KB_SUA]'
GO
CREATE TABLE [dbo].[HL_KB_SUA]
(
[HL_KB_SUAID] [numeric] (18, 0) NOT NULL IDENTITY(1, 1),
[MA_KHO] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[_XORN] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGAY_KB] [datetime] NULL,
[GHI_CHU] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SO_HIEU_PTVT_CU] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SO_CHUYEN_CU] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGAY_TAU_DEN_CU] [datetime] NULL,
[NGAY_VAO_KHO_CU] [datetime] NULL,
[SO_HIEU_PTVT] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SO_CHUYEN] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGAY_TAU_DEN] [datetime] NULL,
[NGAY_VAO_KHO] [datetime] NULL,
[LY_DO_SUA] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HL_KB_NHAPID] [numeric] (18, 0) NULL,
[GUID] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TRANG_THAI] [int] NOT NULL CONSTRAINT [DF_HL_KB_SUA_TRANG_THAI] DEFAULT ((0)),
[SO_TN] [numeric] (18, 0) NULL,
[NGAY_TN] [datetime] NULL,
[MESSAGEID] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGUOI_TAO] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGAY_TAO] [datetime] NULL,
[NGUOI_SUA] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGAY_SUA] [datetime] NULL
)

GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Creating primary key [PK_HL_KB_SUA] on [dbo].[HL_KB_SUA]'
GO
ALTER TABLE [dbo].[HL_KB_SUA] ADD CONSTRAINT [PK_HL_KB_SUA] PRIMARY KEY CLUSTERED  ([HL_KB_SUAID])
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Creating [dbo].[HL_KB_XUAT]'
GO
CREATE TABLE [dbo].[HL_KB_XUAT]
(
[HL_KB_XUATID] [numeric] (18, 0) NOT NULL IDENTITY(1, 1),
[_XORN] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[MA_KHO] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SOTK] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[NGAY_DK] [datetime] NULL,
[MA_LH] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MA_HQ] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGAY_GIO_RA] [datetime] NULL,
[GHI_CHU] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SO_TN] [numeric] (18, 0) NULL,
[NGAY_TN] [datetime] NULL,
[MESSAGEID] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TRANG_THAI] [int] NOT NULL CONSTRAINT [DF_HL_TOKHAI_TRANG_THAI] DEFAULT ((0)),
[GUID] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGUOI_TAO] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGAY_TAO] [datetime] NULL,
[NGUOI_SUA] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGAY_SUA] [datetime] NULL
)

GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Creating primary key [PK_HL_KB_XUAT] on [dbo].[HL_KB_XUAT]'
GO
ALTER TABLE [dbo].[HL_KB_XUAT] ADD CONSTRAINT [PK_HL_KB_XUAT] PRIMARY KEY CLUSTERED  ([HL_KB_XUATID])
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Creating [dbo].[HL_KB_HANGHOA]'
GO
CREATE TABLE [dbo].[HL_KB_HANGHOA]
(
[HL_KB_HANGHOAID] [numeric] (18, 0) NOT NULL IDENTITY(1, 1),
[MA_KHO] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SO_HIEU_PTVT] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HO_HIEU_TAU] [nvarchar] (35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SO_IMO] [nvarchar] (35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SO_CHUYEN] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGAY_TAU_DEN] [datetime] NULL,
[GHI_CHU] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TRANG_THAI] [int] NOT NULL CONSTRAINT [DF_HL_KB_HANGHOA_TRANG_THAI] DEFAULT ((0)),
[SO_TN] [numeric] (18, 0) NULL,
[NGAY_TN] [datetime] NULL,
[MESSAGEID] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GUID] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGUOI_TAO] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGAY_TAO] [datetime] NULL,
[NGUOI_SUA] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGAY_SUA] [datetime] NULL
)

GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Creating primary key [PK_HL_KB_HANGHOA] on [dbo].[HL_KB_HANGHOA]'
GO
ALTER TABLE [dbo].[HL_KB_HANGHOA] ADD CONSTRAINT [PK_HL_KB_HANGHOA] PRIMARY KEY CLUSTERED  ([HL_KB_HANGHOAID])
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Creating [dbo].[HL_KB_NHAP_CT]'
GO
CREATE TABLE [dbo].[HL_KB_NHAP_CT]
(
[HL_KB_NHAP_CTID] [numeric] (18, 0) NOT NULL IDENTITY(1, 1),
[HL_KB_NHAPID] [numeric] (18, 0) NOT NULL,
[SO_VAN_DON] [nvarchar] (35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DINH_DANH_HANG_HOA] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SO_XUAT_KHAU] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SO_LUONG] [float] NULL,
[SO_LUONG_OUT] [float] NULL,
[MA_DVT] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SO_HIEU_PTVT] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SO_CHUYEN] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGAY_TAU_DEN] [datetime] NULL,
[VI_TRI_HANG] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MO_TA_HANG] [nvarchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GHI_CHU] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MA_HINH_THUC] [int] NULL,
[NGAY_VAO_KHO] [datetime] NULL,
[IS_SAIKHAC] [bit] NOT NULL CONSTRAINT [DF_HL_KB_NHAP_CT_IS_SAIKHAC] DEFAULT ((0)),
[IS_HUY] [bit] NOT NULL CONSTRAINT [DF_HL_KB_NHAP_CT_IS_HUY] DEFAULT ((0)),
[IS_XUAT] [bit] NOT NULL CONSTRAINT [DF_HL_KB_NHAP_CT_IS_XUAT] DEFAULT ((0)),
[SOTK_XUAT] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GHI_CHU_HT] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)

GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Creating primary key [PK_HL_KB_NHAP_CT] on [dbo].[HL_KB_NHAP_CT]'
GO
ALTER TABLE [dbo].[HL_KB_NHAP_CT] ADD CONSTRAINT [PK_HL_KB_NHAP_CT] PRIMARY KEY CLUSTERED  ([HL_KB_NHAP_CTID])
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Creating [dbo].[HL_KB_NHAP_CT_TK]'
GO
CREATE TABLE [dbo].[HL_KB_NHAP_CT_TK]
(
[HL_KB_NHAP_CT_TKID] [numeric] (18, 0) NOT NULL IDENTITY(1, 1),
[HL_KB_NHAP_CTID] [numeric] (18, 0) NOT NULL,
[SO_LUONG] [float] NULL,
[MA_DVT] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SOTK] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGAY_DK] [datetime] NULL,
[MA_HQ] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MA_HQ_GIAM_SAT] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MA_LH] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MA_TTTK] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PHAN_LUONG] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MA_DV] [varchar] (17) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TEN_DV] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TRANG_THAI] [int] NOT NULL CONSTRAINT [DF_HL_KB_NHAP_CT_TK_TRANG_THAI] DEFAULT ((0)),
[IS_DU_DK] [bit] NOT NULL CONSTRAINT [DF_HL_KB_NHAP_CT_TK_IS_DU_DK] DEFAULT ((0)),
[IS_XUAT] [bit] NOT NULL CONSTRAINT [DF_HL_KB_NHAP_CT_TK_IS_XUAT] DEFAULT ((0))
)

GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Creating primary key [PK_HL_KB_NHAP_CT_TK] on [dbo].[HL_KB_NHAP_CT_TK]'
GO
ALTER TABLE [dbo].[HL_KB_NHAP_CT_TK] ADD CONSTRAINT [PK_HL_KB_NHAP_CT_TK] PRIMARY KEY CLUSTERED  ([HL_KB_NHAP_CT_TKID])
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Creating [dbo].[HL_KB_SODO]'
GO
CREATE TABLE [dbo].[HL_KB_SODO]
(
[HL_KB_SODOID] [numeric] (18, 0) NOT NULL IDENTITY(1, 1),
[MA_KHO] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TEN_FILE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DUNG_LUONG] [float] NULL,
[NOI_DUNG] [ntext] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TRANG_THAI] [int] NOT NULL CONSTRAINT [DF_HL_KB_SODO_TRANG_THAI] DEFAULT ((0)),
[SO_TN] [numeric] (18, 0) NULL,
[NGAY_TN] [datetime] NULL,
[MESSAGEID] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGUOI_TAO] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGAY_TAO] [datetime] NULL,
[NGUOI_SUA] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGAY_SUA] [datetime] NULL
)

GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Creating primary key [PK_HL_KB_SODO] on [dbo].[HL_KB_SODO]'
GO
ALTER TABLE [dbo].[HL_KB_SODO] ADD CONSTRAINT [PK_HL_KB_SODO] PRIMARY KEY CLUSTERED  ([HL_KB_SODOID])
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Creating [dbo].[HL_KB_SAIKHAC]'
GO
CREATE TABLE [dbo].[HL_KB_SAIKHAC]
(
[HL_KB_SAIKHACID] [numeric] (18, 0) NOT NULL IDENTITY(1, 1),
[MA_KHO] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[NGAY_KB] [datetime] NULL,
[GHI_CHU] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SO_HIEU_PTVT] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SO_CHUYEN] [nvarchar] (35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGAY_TAU_DEN] [datetime] NULL,
[SO_IMO] [nvarchar] (35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HO_HIEU_TAU] [nvarchar] (35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TRANG_THAI] [int] NOT NULL CONSTRAINT [DF_HL_KB_SAIKHAC_TRANG_THAI] DEFAULT ((0)),
[SO_TN] [numeric] (18, 0) NULL,
[NGAY_TN] [datetime] NULL,
[MESSAGEID] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GUID] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGUOI_TAO] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGAY_TAO] [datetime] NULL,
[NGUOI_SUA] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGAY_SUA] [datetime] NULL
)

GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Creating primary key [PK_HL_KB_SAIKHAC] on [dbo].[HL_KB_SAIKHAC]'
GO
ALTER TABLE [dbo].[HL_KB_SAIKHAC] ADD CONSTRAINT [PK_HL_KB_SAIKHAC] PRIMARY KEY CLUSTERED  ([HL_KB_SAIKHACID])
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Adding foreign keys to [dbo].[HL_VANDON_TRACUU]'
GO
ALTER TABLE [dbo].[HL_VANDON_TRACUU] ADD
CONSTRAINT [FK_HL_VANDON_TRACUU_SKHO] FOREIGN KEY ([MA_KHO]) REFERENCES [dbo].[SKHO] ([MA_KHO])
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Adding foreign keys to [dbo].[HL_KB_NHAP_CT]'
GO
ALTER TABLE [dbo].[HL_KB_NHAP_CT] ADD
CONSTRAINT [FK_HL_KB_NHAP_CT_HL_KB_NHAP] FOREIGN KEY ([HL_KB_NHAPID]) REFERENCES [dbo].[HL_KB_NHAP] ([HL_KB_NHAPID])
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Adding foreign keys to [dbo].[HL_KB_HANGHOA]'
GO
ALTER TABLE [dbo].[HL_KB_HANGHOA] ADD
CONSTRAINT [FK_HL_KB_HANGHOA_SKHO] FOREIGN KEY ([MA_KHO]) REFERENCES [dbo].[SKHO] ([MA_KHO])
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Adding foreign keys to [dbo].[HL_KB_THAYDOI_CT]'
GO
ALTER TABLE [dbo].[HL_KB_THAYDOI_CT] ADD
CONSTRAINT [FK_HL_KB_THAYDOI_CT_HL_KB_NHAP_CT] FOREIGN KEY ([HL_KB_NHAP_CTID]) REFERENCES [dbo].[HL_KB_NHAP_CT] ([HL_KB_NHAP_CTID]),
CONSTRAINT [FK_HL_KB_THAYDOI_CT_HL_KB_THAYDOI] FOREIGN KEY ([HL_KB_THAYDOIID]) REFERENCES [dbo].[HL_KB_THAYDOI] ([HL_KB_THAYDOIID])
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Adding foreign keys to [dbo].[HL_KB_XUAT_141_CT]'
GO
ALTER TABLE [dbo].[HL_KB_XUAT_141_CT] ADD
CONSTRAINT [FK_HL_KB_XUAT_141_CT_HL_KB_NHAP_CT] FOREIGN KEY ([HL_KB_NHAP_CTID]) REFERENCES [dbo].[HL_KB_NHAP_CT] ([HL_KB_NHAP_CTID]),
CONSTRAINT [FK_HL_KB_XUAT_141_CT_HL_KB_XUAT_141] FOREIGN KEY ([HL_KB_XUAT_141ID]) REFERENCES [dbo].[HL_KB_XUAT_141] ([HL_KB_XUAT_141ID])
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Adding foreign keys to [dbo].[HL_KB_NHAP]'
GO
ALTER TABLE [dbo].[HL_KB_NHAP] ADD
CONSTRAINT [FK_HL_KB_NHAP_SKHO] FOREIGN KEY ([MA_KHO]) REFERENCES [dbo].[SKHO] ([MA_KHO])
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Adding foreign keys to [dbo].[HL_KB_SUA]'
GO
ALTER TABLE [dbo].[HL_KB_SUA] ADD
CONSTRAINT [FK_HL_KB_SUA_HL_KB_NHAP] FOREIGN KEY ([HL_KB_NHAPID]) REFERENCES [dbo].[HL_KB_NHAP] ([HL_KB_NHAPID]),
CONSTRAINT [FK_HL_KB_SUA_SKHO] FOREIGN KEY ([MA_KHO]) REFERENCES [dbo].[SKHO] ([MA_KHO])
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Adding foreign keys to [dbo].[HL_KB_XUAT_CT]'
GO
ALTER TABLE [dbo].[HL_KB_XUAT_CT] ADD
CONSTRAINT [FK_HL_KB_XUAT_CT_HL_KB_NHAP_CT] FOREIGN KEY ([HL_KB_NHAP_CTID]) REFERENCES [dbo].[HL_KB_NHAP_CT] ([HL_KB_NHAP_CTID]),
CONSTRAINT [FK_HL_KB_XUAT_CT_HL_KB_NHAP_CT_TK] FOREIGN KEY ([HL_KB_NHAP_CT_TKID]) REFERENCES [dbo].[HL_KB_NHAP_CT_TK] ([HL_KB_NHAP_CT_TKID]),
CONSTRAINT [FK_HL_KB_XUAT_CT_HL_KB_XUAT] FOREIGN KEY ([HL_KB_XUATID]) REFERENCES [dbo].[HL_KB_XUAT] ([HL_KB_XUATID])
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Adding foreign keys to [dbo].[HL_KB_THAYDOI]'
GO
ALTER TABLE [dbo].[HL_KB_THAYDOI] ADD
CONSTRAINT [FK_HL_KB_THAYDOI_HL_KB_NHAP] FOREIGN KEY ([HL_KB_NHAPID]) REFERENCES [dbo].[HL_KB_NHAP] ([HL_KB_NHAPID]),
CONSTRAINT [FK_HL_KB_THAYDOI_SKHO] FOREIGN KEY ([MA_KHO]) REFERENCES [dbo].[SKHO] ([MA_KHO])
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Adding foreign keys to [dbo].[HL_KB_SODO]'
GO
ALTER TABLE [dbo].[HL_KB_SODO] ADD
CONSTRAINT [FK_HL_KB_SODO_SKHO] FOREIGN KEY ([MA_KHO]) REFERENCES [dbo].[SKHO] ([MA_KHO])
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Adding foreign keys to [dbo].[HL_KB_SAIKHAC]'
GO
ALTER TABLE [dbo].[HL_KB_SAIKHAC] ADD
CONSTRAINT [FK_HL_KB_SAIKHAC_SKHO] FOREIGN KEY ([MA_KHO]) REFERENCES [dbo].[SKHO] ([MA_KHO])
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Adding foreign keys to [dbo].[HL_KB_NHAP_CT_TK]'
GO
ALTER TABLE [dbo].[HL_KB_NHAP_CT_TK] ADD
CONSTRAINT [FK_HL_KB_NHAP_CT_TK_HL_KB_NHAP_CT] FOREIGN KEY ([HL_KB_NHAP_CTID]) REFERENCES [dbo].[HL_KB_NHAP_CT] ([HL_KB_NHAP_CTID])
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Adding foreign keys to [dbo].[HL_TOKHAI_TRACUU_CT]'
GO
ALTER TABLE [dbo].[HL_TOKHAI_TRACUU_CT] ADD
CONSTRAINT [FK_HL_TOKHAI_TRACUU_CT_HL_TOKHAI_TRACUU] FOREIGN KEY ([HL_TOKHAI_TRACUUID]) REFERENCES [dbo].[HL_TOKHAI_TRACUU] ([HL_TOKHAI_TRACUUID])
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Adding foreign keys to [dbo].[HL_KB_XUAT]'
GO
ALTER TABLE [dbo].[HL_KB_XUAT] ADD
CONSTRAINT [FK_HL_KB_XUAT_SKHO] FOREIGN KEY ([MA_KHO]) REFERENCES [dbo].[SKHO] ([MA_KHO]),
CONSTRAINT [FK_HL_KB_XUAT_SLOAIHINH] FOREIGN KEY ([MA_LH]) REFERENCES [dbo].[SLOAIHINH] ([MA_LH]),
CONSTRAINT [FK_HL_KB_XUAT_SHAIQUAN] FOREIGN KEY ([MA_HQ]) REFERENCES [dbo].[SHAIQUAN] ([MA_HQ])
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Adding foreign keys to [dbo].[HL_KB_SAIKHAC_CT]'
GO
ALTER TABLE [dbo].[HL_KB_SAIKHAC_CT] ADD
CONSTRAINT [FK_HL_KB_SAIKHAC_CT_HL_KB_SAIKHAC] FOREIGN KEY ([HL_KB_SAIKHACID]) REFERENCES [dbo].[HL_KB_SAIKHAC] ([HL_KB_SAIKHACID])
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Adding foreign keys to [dbo].[HL_VANDON_TRACUU_CT]'
GO
ALTER TABLE [dbo].[HL_VANDON_TRACUU_CT] ADD
CONSTRAINT [FK_HL_VANDON_TRACUU_CT_HL_VANDON_TRACUU] FOREIGN KEY ([HL_VANDON_TRACUUID]) REFERENCES [dbo].[HL_VANDON_TRACUU] ([HL_VANDON_TRACUUID]),
CONSTRAINT [FK_HL_VANDON_TRACUU_CT_SHAIQUAN] FOREIGN KEY ([MA_HQ]) REFERENCES [dbo].[SHAIQUAN] ([MA_HQ]),
CONSTRAINT [FK_HL_VANDON_TRACUU_CT_SHAIQUAN1] FOREIGN KEY ([MA_HQ_GIAM_SAT]) REFERENCES [dbo].[SHAIQUAN] ([MA_HQ])
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Adding foreign keys to [dbo].[HL_KB_XUAT_141]'
GO
ALTER TABLE [dbo].[HL_KB_XUAT_141] ADD
CONSTRAINT [FK_HL_KB_XUAT_141_SKHO] FOREIGN KEY ([MA_KHO]) REFERENCES [dbo].[SKHO] ([MA_KHO])
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Adding foreign keys to [dbo].[HL_KB_HANGHOA_CT]'
GO
ALTER TABLE [dbo].[HL_KB_HANGHOA_CT] ADD
CONSTRAINT [FK_HL_KB_HANGHOA_CT_HL_KB_HANGHOA] FOREIGN KEY ([HL_KB_HANGHOAID]) REFERENCES [dbo].[HL_KB_HANGHOA] ([HL_KB_HANGHOAID])
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
IF EXISTS (SELECT * FROM #tmpErrors) ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT>0 BEGIN
--Cập nhật phiên bản CSDL
UPDATE SYSAPP SET GIA_TRI = '18' WHERE DATA_FIELD = 'DBVERSION'
PRINT 'The database updated succeeded'
COMMIT TRANSACTION
END
ELSE PRINT 'The database update failed'
GO
DROP TABLE #tmpErrors
GO
