/*
Script created by SQL Compare from Red Gate Software Ltd at 7/18/2017 2:57:30 PM
Run this script on PC01\SQL2008.ECUS5_CANG_PH to make it the same as PC01\SQL2008.ECUS5_CANG_DEV
Please back up your database before running this script
*/
SET NUMERIC_ROUNDABORT OFF
GO
SET ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, ARITHABORT, QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
IF EXISTS (SELECT * FROM tempdb..sysobjects WHERE id=OBJECT_ID('tempdb..#tmpErrors')) DROP TABLE #tmpErrors
GO
CREATE TABLE #tmpErrors (Error int)
GO
SET XACT_ABORT ON
GO
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
GO
BEGIN TRANSACTION
GO
PRINT N'Dropping foreign keys from [dbo].[HR_KB_HUY]'
GO
ALTER TABLE [dbo].[HR_KB_HUY] DROP
CONSTRAINT [FK_HR_KB_HUY_HR_KB_NHAP_CT]
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Dropping foreign keys from [dbo].[HR_KB_TOKHAI_CT]'
GO
ALTER TABLE [dbo].[HR_KB_TOKHAI_CT] DROP
CONSTRAINT [FK_HR_KB_TOKHAI_CT_HR_KB_TOKHAI],
CONSTRAINT [FK_HR_KB_TOKHAI_CT_HR_KB_NHAP_CT]
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Dropping foreign keys from [dbo].[HR_KB_TOKHAI]'
GO
ALTER TABLE [dbo].[HR_KB_TOKHAI] DROP
CONSTRAINT [FK_HR_KB_TOKHAI_SKHO],
CONSTRAINT [FK_HR_KB_TOKHAI_SLOAIHINH],
CONSTRAINT [FK_HR_KB_TOKHAI_SHAIQUAN]
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Dropping foreign keys from [dbo].[KB_HANGHOA_CT]'
GO
ALTER TABLE [dbo].[KB_HANGHOA_CT] DROP
CONSTRAINT [FK_KB_HANGHOA_CT_KB_HANGHOA]
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Dropping foreign keys from [dbo].[KB_HANGHOA]'
GO
ALTER TABLE [dbo].[KB_HANGHOA] DROP
CONSTRAINT [FK_KB_HANGHOA_SKHO]
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Dropping constraints from [dbo].[HR_KB_TOKHAI]'
GO
ALTER TABLE [dbo].[HR_KB_TOKHAI] DROP CONSTRAINT [PK_HR_KB_TOKHAI]
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Dropping constraints from [dbo].[HR_KB_TOKHAI]'
GO
ALTER TABLE [dbo].[HR_KB_TOKHAI] DROP CONSTRAINT [DF_HR_KB_TOKHAI_TRANG_THAI]
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Dropping constraints from [dbo].[HR_KB_TOKHAI_CT]'
GO
ALTER TABLE [dbo].[HR_KB_TOKHAI_CT] DROP CONSTRAINT [PK_HR_KB_TOKHAI_CT]
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Dropping constraints from [dbo].[KB_HANGHOA]'
GO
ALTER TABLE [dbo].[KB_HANGHOA] DROP CONSTRAINT [PK_KB_HANGHOA]
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Dropping constraints from [dbo].[KB_HANGHOA]'
GO
ALTER TABLE [dbo].[KB_HANGHOA] DROP CONSTRAINT [DF_KB_HANGHOA_TRANG_THAI]
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Dropping constraints from [dbo].[KB_HANGHOA_CT]'
GO
ALTER TABLE [dbo].[KB_HANGHOA_CT] DROP CONSTRAINT [PK_KB_HANGHOA_CT]
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Dropping constraints from [dbo].[HR_KB_NHAP_CT]'
GO
ALTER TABLE [dbo].[HR_KB_NHAP_CT] DROP CONSTRAINT [DF_HR_KB_NHAP_CT_TRANG_THAI]
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Dropping constraints from [dbo].[HR_KB_NHAP_CT]'
GO
ALTER TABLE [dbo].[HR_KB_NHAP_CT] DROP CONSTRAINT [DF_HR_KB_NHAP_CT_IS_DU_DK]
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Dropping [dbo].[KB_HANGHOA]'
GO
DROP TABLE [dbo].[KB_HANGHOA]
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Dropping [dbo].[HR_KB_TOKHAI]'
GO
DROP TABLE [dbo].[HR_KB_TOKHAI]
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Dropping [dbo].[KB_HANGHOA_CT]'
GO
DROP TABLE [dbo].[KB_HANGHOA_CT]
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Dropping [dbo].[HR_KB_TOKHAI_CT]'
GO
DROP TABLE [dbo].[HR_KB_TOKHAI_CT]
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Creating [dbo].[HR_KB_HANGHOA]'
GO
CREATE TABLE [dbo].[HR_KB_HANGHOA]
(
[HR_KB_HANGHOAID] [numeric] (18, 0) NOT NULL IDENTITY(1, 1),
[MA_KHO] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SO_HIEU_PTVT] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HO_HIEU_TAU] [nvarchar] (35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SO_IMO] [nvarchar] (35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SO_CHUYEN] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGAY_TAU_DEN] [datetime] NULL,
[GHI_CHU] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TRANG_THAI] [int] NOT NULL CONSTRAINT [DF_HR_KB_HANGHOA_TRANG_THAI] DEFAULT ((0)),
[SO_TN] [numeric] (18, 0) NULL,
[NGAY_TN] [datetime] NULL,
[MESSAGEID] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GUID] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGUOI_TAO] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGAY_TAO] [datetime] NULL,
[NGUOI_SUA] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGAY_SUA] [datetime] NULL
)

GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Creating primary key [PK_HR_KB_HANGHOA] on [dbo].[HR_KB_HANGHOA]'
GO
ALTER TABLE [dbo].[HR_KB_HANGHOA] ADD CONSTRAINT [PK_HR_KB_HANGHOA] PRIMARY KEY CLUSTERED  ([HR_KB_HANGHOAID])
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Creating [dbo].[HK_KB_HANGHOA]'
GO
CREATE TABLE [dbo].[HK_KB_HANGHOA]
(
[HK_KB_HANGHOAID] [numeric] (18, 0) NOT NULL IDENTITY(1, 1),
[MA_KHO] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SO_HIEU_PTVT] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HO_HIEU_TAU] [nvarchar] (35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SO_IMO] [nvarchar] (35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SO_CHUYEN] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGAY_TAU_DEN] [datetime] NULL,
[GHI_CHU] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TRANG_THAI] [int] NOT NULL CONSTRAINT [DF_HK_KB_HANGHOA_TRANG_THAI] DEFAULT ((0)),
[SO_TN] [numeric] (18, 0) NULL,
[NGAY_TN] [datetime] NULL,
[MESSAGEID] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GUID] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGUOI_TAO] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGAY_TAO] [datetime] NULL,
[NGUOI_SUA] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGAY_SUA] [datetime] NULL
)

GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Creating primary key [PK_HK_KB_HANGHOA] on [dbo].[HK_KB_HANGHOA]'
GO
ALTER TABLE [dbo].[HK_KB_HANGHOA] ADD CONSTRAINT [PK_HK_KB_HANGHOA] PRIMARY KEY CLUSTERED  ([HK_KB_HANGHOAID])
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Creating [dbo].[HK_KB_HANGHOA_CT]'
GO
CREATE TABLE [dbo].[HK_KB_HANGHOA_CT]
(
[HK_KB_HANGHOA_CTID] [numeric] (18, 0) NOT NULL IDENTITY(1, 1),
[HK_KB_HANGHOAID] [numeric] (18, 0) NULL,
[SO_VAN_DON] [nvarchar] (35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DINH_DANH_HANG_HOA] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SO_LUONG] [float] NULL,
[MA_DVT] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)

GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Creating primary key [PK_HK_KB_HANGHOA_CT] on [dbo].[HK_KB_HANGHOA_CT]'
GO
ALTER TABLE [dbo].[HK_KB_HANGHOA_CT] ADD CONSTRAINT [PK_HK_KB_HANGHOA_CT] PRIMARY KEY CLUSTERED  ([HK_KB_HANGHOA_CTID])
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Creating [dbo].[HR_KB_XUAT_CT]'
GO
CREATE TABLE [dbo].[HR_KB_XUAT_CT]
(
[HR_KB_XUAT_CTID] [numeric] (18, 0) NOT NULL IDENTITY(1, 1),
[HR_KB_XUATID] [numeric] (18, 0) NULL,
[HR_KB_NHAP_CTID] [numeric] (18, 0) NULL,
[HR_KB_NHAP_CT_TKID] [numeric] (18, 0) NULL,
[SO_HIEU_PTVT] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SO_CHUYEN] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGAY_TAU_DEN] [datetime] NULL,
[SO_VAN_DON] [nvarchar] (35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DINH_DANH_HANG_HOA] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SO_LUONG] [float] NULL,
[MA_DVT] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GHI_CHU] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MA_HINH_THUC] [int] NULL
)

GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Creating primary key [PK_HR_KB_XUAT_CT] on [dbo].[HR_KB_XUAT_CT]'
GO
ALTER TABLE [dbo].[HR_KB_XUAT_CT] ADD CONSTRAINT [PK_HR_KB_XUAT_CT] PRIMARY KEY CLUSTERED  ([HR_KB_XUAT_CTID])
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Creating [dbo].[HK_KB_XUAT_CT]'
GO
CREATE TABLE [dbo].[HK_KB_XUAT_CT]
(
[HK_KB_XUAT_CTID] [numeric] (18, 0) NOT NULL IDENTITY(1, 1),
[HK_KB_XUATID] [numeric] (18, 0) NULL,
[HK_KB_NHAP_CTID] [numeric] (18, 0) NULL,
[HK_KB_NHAP_CT_TKID] [numeric] (18, 0) NULL,
[SO_HIEU_PTVT] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SO_CHUYEN] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGAY_TAU_DEN] [datetime] NULL,
[SO_VAN_DON] [nvarchar] (35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DINH_DANH_HANG_HOA] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SO_LUONG] [int] NULL,
[MA_DVT] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GHI_CHU] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MA_HINH_THUC] [int] NULL
)

GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Creating primary key [PK_HK_KB_XUAT_CT] on [dbo].[HK_KB_XUAT_CT]'
GO
ALTER TABLE [dbo].[HK_KB_XUAT_CT] ADD CONSTRAINT [PK_HK_KB_XUAT_CT] PRIMARY KEY CLUSTERED  ([HK_KB_XUAT_CTID])
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Creating [dbo].[HR_VANDON_TRACUU_CT]'
GO
CREATE TABLE [dbo].[HR_VANDON_TRACUU_CT]
(
[HR_VANDON_TRACUU_CTID] [numeric] (18, 0) NOT NULL IDENTITY(1, 1),
[HR_VANDON_TRACUUID] [numeric] (18, 0) NOT NULL,
[SOTK] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGAY_DK] [datetime] NULL,
[MA_LH] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MA_HQ] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MA_HQ_GIAM_SAT] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PHAN_LUONG] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MA_DV] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TEN_DV] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MA_TTTK] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[THOI_GIAN_KET_XUAT] [datetime] NULL,
[SO_LUONG] [float] NULL,
[MA_DVT] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)

GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Creating primary key [PK_HR_VANDON_TRACUU_CT] on [dbo].[HR_VANDON_TRACUU_CT]'
GO
ALTER TABLE [dbo].[HR_VANDON_TRACUU_CT] ADD CONSTRAINT [PK_HR_VANDON_TRACUU_CT] PRIMARY KEY CLUSTERED  ([HR_VANDON_TRACUU_CTID])
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Creating [dbo].[CONT_KB_SOICHIEU]'
GO
CREATE TABLE [dbo].[CONT_KB_SOICHIEU]
(
[CONT_KB_SOICHIEUID] [numeric] (18, 0) NOT NULL IDENTITY(1, 1),
[MA_KHO] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[_XORN] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGAY_BAT_DAU] [datetime] NULL,
[NGAY_KET_THUC] [datetime] NULL,
[GHI_CHU] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TRANG_THAI] [int] NOT NULL CONSTRAINT [DF_CONT_KB_SOICHIEU_TRANG_THAI] DEFAULT ((0)),
[GUID] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SO_TN] [numeric] (18, 0) NULL,
[NGAY_TN] [datetime] NULL,
[MESSAGEID] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGUOI_TAO] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGAY_TAO] [datetime] NULL,
[NGUOI_SUA] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGAY_SUA] [datetime] NULL
)

GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Creating primary key [PK_CONT_KB_SOICHIEU] on [dbo].[CONT_KB_SOICHIEU]'
GO
ALTER TABLE [dbo].[CONT_KB_SOICHIEU] ADD CONSTRAINT [PK_CONT_KB_SOICHIEU] PRIMARY KEY CLUSTERED  ([CONT_KB_SOICHIEUID])
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Creating [dbo].[CONT_KB_SOICHIEU_CT]'
GO
CREATE TABLE [dbo].[CONT_KB_SOICHIEU_CT]
(
[CONT_KB_SOICHIEU_CTID] [numeric] (18, 0) NOT NULL IDENTITY(1, 1),
[CONT_KB_SOICHIEUID] [numeric] (18, 0) NULL,
[SO_HIEU_PTVT] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SOTK] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SO_VAN_DON] [nvarchar] (35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SO_CONTAINER] [nvarchar] (35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SO_SEAL] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)

GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Creating primary key [PK_CONT_KB_SOICHIEU_CT] on [dbo].[CONT_KB_SOICHIEU_CT]'
GO
ALTER TABLE [dbo].[CONT_KB_SOICHIEU_CT] ADD CONSTRAINT [PK_CONT_KB_SOICHIEU_CT] PRIMARY KEY CLUSTERED  ([CONT_KB_SOICHIEU_CTID])
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Creating [dbo].[HK_KB_HUY]'
GO
CREATE TABLE [dbo].[HK_KB_HUY]
(
[HK_KB_HUYID] [numeric] (18, 0) NOT NULL IDENTITY(1, 1),
[_XORN] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MA_KHO] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[HK_KB_NHAP_CTID] [numeric] (18, 0) NOT NULL,
[NGAY_KB] [datetime] NULL,
[LY_DO_HUY] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GHI_CHU] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GUID] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SO_TN] [numeric] (18, 0) NULL,
[NGAY_TN] [datetime] NULL,
[MESSAGEID] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TRANG_THAI] [int] NOT NULL CONSTRAINT [DF_HK_KB_HUY_TRANG_THAI] DEFAULT ((0)),
[NGUOI_TAO] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGAY_TAO] [datetime] NULL,
[NGUOI_SUA] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGAY_SUA] [datetime] NULL
)

GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Creating primary key [PK_HK_KB_HUY] on [dbo].[HK_KB_HUY]'
GO
ALTER TABLE [dbo].[HK_KB_HUY] ADD CONSTRAINT [PK_HK_KB_HUY] PRIMARY KEY CLUSTERED  ([HK_KB_HUYID])
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Creating [dbo].[HK_TOKHAI_TRACUU]'
GO
CREATE TABLE [dbo].[HK_TOKHAI_TRACUU]
(
[HK_TOKHAI_TRACUUID] [numeric] (18, 0) NOT NULL IDENTITY(1, 1),
[MA_KHO] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SOTK] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGAY_DK] [datetime] NULL,
[MA_LH] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MA_HQ] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LOAI_TC] [int] NULL,
[MA_HQ_GIAM_SAT] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PHAN_LUONG] [nchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MA_TTTK] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MA_DV] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TEN_DV] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[THOI_GIAN_KET_XUAT] [datetime] NULL,
[NOI_DUNG_PHAN_HOI] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TRANG_THAI] [int] NOT NULL CONSTRAINT [DF_HK_TOKHAI_TRACUU_TRANG_THAI] DEFAULT ((0)),
[GUID] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SO_TN] [bigint] NULL,
[NGAY_TN] [datetime] NULL,
[MESSAGEID] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MESSAGEID_KT] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGUOI_TAO] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGAY_TAO] [datetime] NULL,
[NGUOI_SUA] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGAY_SUA] [datetime] NULL
)

GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Creating primary key [PK_HK_TOKHAI_TRACUU] on [dbo].[HK_TOKHAI_TRACUU]'
GO
ALTER TABLE [dbo].[HK_TOKHAI_TRACUU] ADD CONSTRAINT [PK_HK_TOKHAI_TRACUU] PRIMARY KEY CLUSTERED  ([HK_TOKHAI_TRACUUID])
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Creating [dbo].[HR_KB_HANGHOA_CT]'
GO
CREATE TABLE [dbo].[HR_KB_HANGHOA_CT]
(
[HR_KB_HANGHOA_CTID] [numeric] (18, 0) NOT NULL IDENTITY(1, 1),
[HR_KB_HANGHOAID] [numeric] (18, 0) NULL,
[SO_VAN_DON] [nvarchar] (35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DINH_DANH_HANG_HOA] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SO_LUONG] [float] NULL,
[MA_DVT] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)

GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Creating primary key [PK_HR_KB_HANGHOA_CT] on [dbo].[HR_KB_HANGHOA_CT]'
GO
ALTER TABLE [dbo].[HR_KB_HANGHOA_CT] ADD CONSTRAINT [PK_HR_KB_HANGHOA_CT] PRIMARY KEY CLUSTERED  ([HR_KB_HANGHOA_CTID])
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Creating [dbo].[HK_VANDON_TRACUU_CT]'
GO
CREATE TABLE [dbo].[HK_VANDON_TRACUU_CT]
(
[HK_VANDON_TRACUU_CTID] [numeric] (18, 0) NOT NULL IDENTITY(1, 1),
[HK_VANDON_TRACUUID] [numeric] (18, 0) NOT NULL,
[SOTK] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGAY_DK] [datetime] NULL,
[MA_LH] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MA_HQ] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MA_HQ_GIAM_SAT] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PHAN_LUONG] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MA_DV] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TEN_DV] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MA_TTTK] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[THOI_GIAN_KET_XUAT] [datetime] NULL,
[SO_LUONG] [int] NULL,
[MA_DVT] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)

GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Creating primary key [PK_HK_VANDON_TRACUU_CT] on [dbo].[HK_VANDON_TRACUU_CT]'
GO
ALTER TABLE [dbo].[HK_VANDON_TRACUU_CT] ADD CONSTRAINT [PK_HK_VANDON_TRACUU_CT] PRIMARY KEY CLUSTERED  ([HK_VANDON_TRACUU_CTID])
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Creating [dbo].[HK_TOKHAI_TRACUU_CT]'
GO
CREATE TABLE [dbo].[HK_TOKHAI_TRACUU_CT]
(
[HK_TOKHAI_TRACUU_CTID] [numeric] (18, 0) NOT NULL IDENTITY(1, 1),
[HK_TOKHAI_TRACUUID] [numeric] (18, 0) NOT NULL,
[SO_HIEU_PTVT] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SO_CHUYEN] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGAY_TAU_DEN] [datetime] NULL,
[SO_VAN_DON] [nvarchar] (35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DINH_DANH_HANG_HOA] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SO_LUONG] [int] NULL,
[MA_DVT] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VI_TRI_HANG] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MO_TA_HANG] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GHI_CHU] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)

GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Creating primary key [PK_HK_TOKHAI_TRACUU_CT] on [dbo].[HK_TOKHAI_TRACUU_CT]'
GO
ALTER TABLE [dbo].[HK_TOKHAI_TRACUU_CT] ADD CONSTRAINT [PK_HK_TOKHAI_TRACUU_CT] PRIMARY KEY CLUSTERED  ([HK_TOKHAI_TRACUU_CTID])
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Creating [dbo].[HR_KB_NHAP_CT_TK]'
GO
CREATE TABLE [dbo].[HR_KB_NHAP_CT_TK]
(
[HR_KB_NHAP_CT_TKID] [numeric] (18, 0) NOT NULL IDENTITY(1, 1),
[HR_KB_NHAP_CTID] [numeric] (18, 0) NOT NULL,
[SO_LUONG] [float] NULL,
[MA_DVT] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SOTK] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGAY_DK] [datetime] NULL,
[MA_HQ] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MA_HQ_GIAM_SAT] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MA_LH] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MA_TTTK] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PHAN_LUONG] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MA_DV] [varchar] (17) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TEN_DV] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TRANG_THAI] [int] NOT NULL CONSTRAINT [DF_HR_KB_NHAP_CT_TK_TRANG_THAI] DEFAULT ((0)),
[IS_DU_DK] [bit] NOT NULL CONSTRAINT [DF_HR_KB_NHAP_CT_TK_IS_DU_DK] DEFAULT ((0)),
[IS_XUAT] [bit] NOT NULL CONSTRAINT [DF_HR_KB_NHAP_CT_TK_IS_XUAT] DEFAULT ((0))
)

GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Creating primary key [PK_HR_KB_NHAP_CT_TK] on [dbo].[HR_KB_NHAP_CT_TK]'
GO
ALTER TABLE [dbo].[HR_KB_NHAP_CT_TK] ADD CONSTRAINT [PK_HR_KB_NHAP_CT_TK] PRIMARY KEY CLUSTERED  ([HR_KB_NHAP_CT_TKID])
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Creating [dbo].[HK_KB_NHAP_CT]'
GO
CREATE TABLE [dbo].[HK_KB_NHAP_CT]
(
[HK_KB_NHAP_CTID] [numeric] (18, 0) NOT NULL IDENTITY(1, 1),
[HK_KB_NHAPID] [numeric] (18, 0) NOT NULL,
[SO_VAN_DON] [nvarchar] (35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DINH_DANH_HANG_HOA] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SO_XUAT_KHAU] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SO_LUONG] [int] NULL,
[MA_DVT] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SO_HIEU_PTVT] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SO_CHUYEN] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGAY_TAU_DEN] [datetime] NULL,
[VI_TRI_HANG] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MO_TA_HANG] [nvarchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GHI_CHU] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MA_HINH_THUC] [int] NULL,
[NGAY_VAO_KHO] [datetime] NULL,
[IS_SAIKHAC] [bit] NOT NULL CONSTRAINT [DF_HK_KB_NHAP_CT_IS_SAIKHAC] DEFAULT ((0)),
[IS_HUY] [bit] NOT NULL CONSTRAINT [DF_HK_KB_NHAP_CT_IS_HUY] DEFAULT ((0)),
[IS_XUAT] [bit] NOT NULL CONSTRAINT [DF_HK_KB_NHAP_CT_IS_XUAT] DEFAULT ((0))
)

GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Creating primary key [PK_HK_KB_NHAP_CT] on [dbo].[HK_KB_NHAP_CT]'
GO
ALTER TABLE [dbo].[HK_KB_NHAP_CT] ADD CONSTRAINT [PK_HK_KB_NHAP_CT] PRIMARY KEY CLUSTERED  ([HK_KB_NHAP_CTID])
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Altering [dbo].[HR_KB_NHAP_CT]'
GO
ALTER TABLE [dbo].[HR_KB_NHAP_CT] ADD
[SO_XUAT_KHAU] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IS_SAIKHAC] [bit] NOT NULL CONSTRAINT [DF_HR_KB_NHAP_CT_IS_SAIKHAC] DEFAULT ((0)),
[IS_HUY] [bit] NOT NULL CONSTRAINT [DF_HR_KB_NHAP_CT_IS_HUY] DEFAULT ((0)),
[IS_XUAT] [bit] NOT NULL CONSTRAINT [DF_HR_KB_NHAP_CT_IS_XUAT] DEFAULT ((0))
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
ALTER TABLE [dbo].[HR_KB_NHAP_CT] DROP
COLUMN [TRANG_THAI],
COLUMN [SOTK],
COLUMN [NGAY_DK],
COLUMN [MA_HQ],
COLUMN [MA_HQ_GIAM_SAT],
COLUMN [MA_LH],
COLUMN [PHAN_LUONG],
COLUMN [MA_TTTK],
COLUMN [MA_DV],
COLUMN [TEN_DV],
COLUMN [IS_DU_DK]
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Creating [dbo].[HR_KB_XUAT]'
GO
CREATE TABLE [dbo].[HR_KB_XUAT]
(
[HR_KB_XUATID] [numeric] (18, 0) NOT NULL IDENTITY(1, 1),
[_XORN] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[MA_KHO] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SOTK] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[NGAY_DK] [datetime] NULL,
[MA_LH] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MA_HQ] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGAY_GIO_RA] [datetime] NULL,
[GHI_CHU] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SO_TN] [numeric] (18, 0) NULL,
[NGAY_TN] [datetime] NULL,
[MESSAGEID] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TRANG_THAI] [int] NOT NULL CONSTRAINT [DF_HR_TOKHAI_TRANG_THAI] DEFAULT ((0)),
[GUID] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGUOI_TAO] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGAY_TAO] [datetime] NULL,
[NGUOI_SUA] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGAY_SUA] [datetime] NULL
)

GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Creating primary key [PK_HR_KB_XUAT] on [dbo].[HR_KB_XUAT]'
GO
ALTER TABLE [dbo].[HR_KB_XUAT] ADD CONSTRAINT [PK_HR_KB_XUAT] PRIMARY KEY CLUSTERED  ([HR_KB_XUATID])
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Creating [dbo].[HK_KB_NHAP]'
GO
CREATE TABLE [dbo].[HK_KB_NHAP]
(
[HK_KB_NHAPID] [numeric] (18, 0) NOT NULL IDENTITY(1, 1),
[MA_KHO] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[_XORN] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SO_HIEU_PTVT] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SO_CHUYEN] [nvarchar] (35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGAY_TAU_DEN] [datetime] NULL,
[NGAY_KB] [datetime] NULL,
[GHI_CHU] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TONG_SO_KIEN] [int] NULL,
[TRANG_THAI] [int] NOT NULL CONSTRAINT [DF_HK_KB_NHAP_TRANG_THAI] DEFAULT ((0)),
[SO_TN] [numeric] (18, 0) NULL,
[NGAY_TN] [datetime] NULL,
[SO_TN_SUA] [numeric] (18, 0) NULL,
[NGAY_TN_SUA] [datetime] NULL,
[MESSAGEID] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GUID] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGUOI_TAO] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGAY_TAO] [datetime] NULL,
[NGUOI_SUA] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGAY_SUA] [datetime] NULL
)

GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Creating primary key [PK_HK_KB_NHAP] on [dbo].[HK_KB_NHAP]'
GO
ALTER TABLE [dbo].[HK_KB_NHAP] ADD CONSTRAINT [PK_HK_KB_NHAP] PRIMARY KEY CLUSTERED  ([HK_KB_NHAPID])
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Creating [dbo].[HK_KB_NHAP_CT_TK]'
GO
CREATE TABLE [dbo].[HK_KB_NHAP_CT_TK]
(
[HK_KB_NHAP_CT_TKID] [numeric] (18, 0) NOT NULL IDENTITY(1, 1),
[HK_KB_NHAP_CTID] [numeric] (18, 0) NOT NULL,
[SO_LUONG] [float] NULL,
[MA_DVT] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SOTK] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGAY_DK] [datetime] NULL,
[MA_HQ] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MA_HQ_GIAM_SAT] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MA_LH] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MA_TTTK] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PHAN_LUONG] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MA_DV] [varchar] (17) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TEN_DV] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TRANG_THAI] [int] NOT NULL CONSTRAINT [DF_HK_KB_NHAP_CT_TK_TRANG_THAI] DEFAULT ((0)),
[IS_DU_DK] [bit] NOT NULL CONSTRAINT [DF_HK_KB_NHAP_CT_TK_IS_DU_DK] DEFAULT ((0)),
[IS_XUAT] [bit] NOT NULL CONSTRAINT [DF_HK_KB_NHAP_CT_TK_IS_XUAT] DEFAULT ((0))
)

GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Creating primary key [PK_HK_KB_NHAP_CT_TK] on [dbo].[HK_KB_NHAP_CT_TK]'
GO
ALTER TABLE [dbo].[HK_KB_NHAP_CT_TK] ADD CONSTRAINT [PK_HK_KB_NHAP_CT_TK] PRIMARY KEY CLUSTERED  ([HK_KB_NHAP_CT_TKID])
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Creating [dbo].[HK_KB_XUAT]'
GO
CREATE TABLE [dbo].[HK_KB_XUAT]
(
[HK_KB_XUATID] [numeric] (18, 0) NOT NULL IDENTITY(1, 1),
[_XORN] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[MA_KHO] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SOTK] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[NGAY_DK] [datetime] NULL,
[MA_LH] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MA_HQ] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGAY_GIO_RA] [datetime] NULL,
[GHI_CHU] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SO_TN] [numeric] (18, 0) NULL,
[NGAY_TN] [datetime] NULL,
[MESSAGEID] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TRANG_THAI] [int] NOT NULL CONSTRAINT [DF_HK_TOKHAI_TRANG_THAI] DEFAULT ((0)),
[GUID] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGUOI_TAO] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGAY_TAO] [datetime] NULL,
[NGUOI_SUA] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGAY_SUA] [datetime] NULL
)

GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Creating primary key [PK_HK_KB_XUAT] on [dbo].[HK_KB_XUAT]'
GO
ALTER TABLE [dbo].[HK_KB_XUAT] ADD CONSTRAINT [PK_HK_KB_XUAT] PRIMARY KEY CLUSTERED  ([HK_KB_XUATID])
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Altering [dbo].[HR_KB_NHAP]'
GO
ALTER TABLE [dbo].[HR_KB_NHAP] ADD
[TONG_SO_KIEN] [int] NULL
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
ALTER TABLE [dbo].[HR_KB_NHAP] DROP
COLUMN [TONG_SO_LUONG]
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Creating [dbo].[HK_KB_SUA]'
GO
CREATE TABLE [dbo].[HK_KB_SUA]
(
[HK_KB_SUAID] [numeric] (18, 0) NOT NULL IDENTITY(1, 1),
[MA_KHO] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[_XORN] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGAY_KB] [datetime] NULL,
[GHI_CHU] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SO_HIEU_PTVT_CU] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SO_CHUYEN_CU] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGAY_TAU_DEN_CU] [datetime] NULL,
[NGAY_VAO_KHO_CU] [datetime] NULL,
[SO_HIEU_PTVT] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SO_CHUYEN] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGAY_TAU_DEN] [datetime] NULL,
[NGAY_VAO_KHO] [datetime] NULL,
[LY_DO_SUA] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HK_KB_NHAPID] [numeric] (18, 0) NULL,
[GUID] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TRANG_THAI] [int] NOT NULL CONSTRAINT [DF_HK_KB_SUA_TRANG_THAI] DEFAULT ((0)),
[SO_TN] [numeric] (18, 0) NULL,
[NGAY_TN] [datetime] NULL,
[MESSAGEID] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGUOI_TAO] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGAY_TAO] [datetime] NULL,
[NGUOI_SUA] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGAY_SUA] [datetime] NULL
)

GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Creating primary key [PK_HK_KB_SUA] on [dbo].[HK_KB_SUA]'
GO
ALTER TABLE [dbo].[HK_KB_SUA] ADD CONSTRAINT [PK_HK_KB_SUA] PRIMARY KEY CLUSTERED  ([HK_KB_SUAID])
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Creating [dbo].[HK_VANDON_TRACUU]'
GO
CREATE TABLE [dbo].[HK_VANDON_TRACUU]
(
[HK_VANDON_TRACUUID] [numeric] (18, 0) NOT NULL IDENTITY(1, 1),
[MA_KHO] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[_XORN] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SO_HIEU_PTVT] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SO_CHUYEN] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGAY_TAU_DEN] [datetime] NULL,
[SO_VAN_DON] [nvarchar] (35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DINH_DANH_HANG_HOA] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VI_TRI_HANG] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MO_TA_HANG] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GHI_CHU] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TRANG_THAI] [int] NOT NULL CONSTRAINT [DF_HK_VANDON_TRACUU_TRANG_THAI] DEFAULT ((0)),
[GUID] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SO_TN] [numeric] (18, 0) NULL,
[NGAY_TN] [datetime] NULL,
[MESSAGEID] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGUOI_TAO] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGAY_TAO] [datetime] NULL,
[NGUOI_SUA] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGAY_SUA] [datetime] NULL
)

GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Creating primary key [PK_HK_VANDON_TRACUU] on [dbo].[HK_VANDON_TRACUU]'
GO
ALTER TABLE [dbo].[HK_VANDON_TRACUU] ADD CONSTRAINT [PK_HK_VANDON_TRACUU] PRIMARY KEY CLUSTERED  ([HK_VANDON_TRACUUID] DESC)
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Creating [dbo].[HR_VANDON_TRACUU]'
GO
CREATE TABLE [dbo].[HR_VANDON_TRACUU]
(
[HR_VANDON_TRACUUID] [numeric] (18, 0) NOT NULL IDENTITY(1, 1),
[MA_KHO] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[_XORN] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SO_HIEU_PTVT] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SO_CHUYEN] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGAY_TAU_DEN] [datetime] NULL,
[SO_VAN_DON] [nvarchar] (35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DINH_DANH_HANG_HOA] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VI_TRI_HANG] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MO_TA_HANG] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GHI_CHU] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TRANG_THAI] [int] NOT NULL CONSTRAINT [DF_HR_VANDON_TRACUU_TRANG_THAI] DEFAULT ((0)),
[GUID] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SO_TN] [numeric] (18, 0) NULL,
[NGAY_TN] [datetime] NULL,
[MESSAGEID] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGUOI_TAO] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGAY_TAO] [datetime] NULL,
[NGUOI_SUA] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGAY_SUA] [datetime] NULL
)

GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Creating primary key [PK_HR_VANDON_TRACUU] on [dbo].[HR_VANDON_TRACUU]'
GO
ALTER TABLE [dbo].[HR_VANDON_TRACUU] ADD CONSTRAINT [PK_HR_VANDON_TRACUU] PRIMARY KEY CLUSTERED  ([HR_VANDON_TRACUUID] DESC)
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Adding foreign keys to [dbo].[HR_KB_HANGHOA_CT]'
GO
ALTER TABLE [dbo].[HR_KB_HANGHOA_CT] ADD
CONSTRAINT [FK_HR_KB_HANGHOA_CT_HR_KB_HANGHOA] FOREIGN KEY ([HR_KB_HANGHOAID]) REFERENCES [dbo].[HR_KB_HANGHOA] ([HR_KB_HANGHOAID])
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Adding foreign keys to [dbo].[HK_KB_HANGHOA_CT]'
GO
ALTER TABLE [dbo].[HK_KB_HANGHOA_CT] ADD
CONSTRAINT [FK_HK_KB_HANGHOA_CT_HK_KB_HANGHOA] FOREIGN KEY ([HK_KB_HANGHOAID]) REFERENCES [dbo].[HK_KB_HANGHOA] ([HK_KB_HANGHOAID])
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Adding foreign keys to [dbo].[HR_KB_NHAP_CT_TK]'
GO
ALTER TABLE [dbo].[HR_KB_NHAP_CT_TK] ADD
CONSTRAINT [FK_HR_KB_NHAP_CT_TK_HR_KB_NHAP_CT] FOREIGN KEY ([HR_KB_NHAP_CTID]) REFERENCES [dbo].[HR_KB_NHAP_CT] ([HR_KB_NHAP_CTID])
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Adding foreign keys to [dbo].[HR_KB_HANGHOA]'
GO
ALTER TABLE [dbo].[HR_KB_HANGHOA] ADD
CONSTRAINT [FK_HR_KB_HANGHOA_SKHO] FOREIGN KEY ([MA_KHO]) REFERENCES [dbo].[SKHO] ([MA_KHO])
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Adding foreign keys to [dbo].[HR_KB_XUAT]'
GO
ALTER TABLE [dbo].[HR_KB_XUAT] ADD
CONSTRAINT [FK_HR_KB_XUAT_SKHO] FOREIGN KEY ([MA_KHO]) REFERENCES [dbo].[SKHO] ([MA_KHO]),
CONSTRAINT [FK_HR_KB_XUAT_SLOAIHINH] FOREIGN KEY ([MA_LH]) REFERENCES [dbo].[SLOAIHINH] ([MA_LH]),
CONSTRAINT [FK_HR_KB_XUAT_SHAIQUAN] FOREIGN KEY ([MA_HQ]) REFERENCES [dbo].[SHAIQUAN] ([MA_HQ])
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Adding foreign keys to [dbo].[HK_KB_XUAT_CT]'
GO
ALTER TABLE [dbo].[HK_KB_XUAT_CT] ADD
CONSTRAINT [FK_HK_KB_XUAT_CT_HK_KB_NHAP_CT] FOREIGN KEY ([HK_KB_NHAP_CTID]) REFERENCES [dbo].[HK_KB_NHAP_CT] ([HK_KB_NHAP_CTID]),
CONSTRAINT [FK_HK_KB_XUAT_CT_HK_KB_NHAP_CT_TK] FOREIGN KEY ([HK_KB_NHAP_CT_TKID]) REFERENCES [dbo].[HK_KB_NHAP_CT_TK] ([HK_KB_NHAP_CT_TKID]),
CONSTRAINT [FK_HK_KB_XUAT_CT_HK_KB_XUAT] FOREIGN KEY ([HK_KB_XUATID]) REFERENCES [dbo].[HK_KB_XUAT] ([HK_KB_XUATID])
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Adding foreign keys to [dbo].[HR_VANDON_TRACUU_CT]'
GO
ALTER TABLE [dbo].[HR_VANDON_TRACUU_CT] ADD
CONSTRAINT [FK_HR_VANDON_TRACUU_CT_HR_VANDON_TRACUU] FOREIGN KEY ([HR_VANDON_TRACUUID]) REFERENCES [dbo].[HR_VANDON_TRACUU] ([HR_VANDON_TRACUUID]),
CONSTRAINT [FK_HR_VANDON_TRACUU_CT_SHAIQUAN] FOREIGN KEY ([MA_HQ]) REFERENCES [dbo].[SHAIQUAN] ([MA_HQ]),
CONSTRAINT [FK_HR_VANDON_TRACUU_CT_SHAIQUAN1] FOREIGN KEY ([MA_HQ_GIAM_SAT]) REFERENCES [dbo].[SHAIQUAN] ([MA_HQ])
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Adding foreign keys to [dbo].[HR_VANDON_TRACUU]'
GO
ALTER TABLE [dbo].[HR_VANDON_TRACUU] ADD
CONSTRAINT [FK_HR_VANDON_TRACUU_SKHO] FOREIGN KEY ([MA_KHO]) REFERENCES [dbo].[SKHO] ([MA_KHO])
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Adding foreign keys to [dbo].[CONT_KB_SOICHIEU]'
GO
ALTER TABLE [dbo].[CONT_KB_SOICHIEU] ADD
CONSTRAINT [FK_CONT_KB_SOICHIEU_SKHO] FOREIGN KEY ([MA_KHO]) REFERENCES [dbo].[SKHO] ([MA_KHO])
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Adding foreign keys to [dbo].[HK_KB_NHAP]'
GO
ALTER TABLE [dbo].[HK_KB_NHAP] ADD
CONSTRAINT [FK_HK_KB_NHAP_SKHO] FOREIGN KEY ([MA_KHO]) REFERENCES [dbo].[SKHO] ([MA_KHO])
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Adding foreign keys to [dbo].[HK_KB_HANGHOA]'
GO
ALTER TABLE [dbo].[HK_KB_HANGHOA] ADD
CONSTRAINT [FK_HK_KB_HANGHOA_SKHO] FOREIGN KEY ([MA_KHO]) REFERENCES [dbo].[SKHO] ([MA_KHO])
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Adding foreign keys to [dbo].[HK_KB_NHAP_CT_TK]'
GO
ALTER TABLE [dbo].[HK_KB_NHAP_CT_TK] ADD
CONSTRAINT [FK_HK_KB_NHAP_CT_TK_HK_KB_NHAP_CT] FOREIGN KEY ([HK_KB_NHAP_CTID]) REFERENCES [dbo].[HK_KB_NHAP_CT] ([HK_KB_NHAP_CTID])
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Adding foreign keys to [dbo].[HR_KB_XUAT_CT]'
GO
ALTER TABLE [dbo].[HR_KB_XUAT_CT] ADD
CONSTRAINT [FK_HR_KB_XUAT_CT_HR_KB_NHAP_CT_TK] FOREIGN KEY ([HR_KB_NHAP_CT_TKID]) REFERENCES [dbo].[HR_KB_NHAP_CT_TK] ([HR_KB_NHAP_CT_TKID]),
CONSTRAINT [FK_HR_KB_XUAT_CT_HR_KB_XUAT] FOREIGN KEY ([HR_KB_XUATID]) REFERENCES [dbo].[HR_KB_XUAT] ([HR_KB_XUATID]),
CONSTRAINT [FK_HR_KB_XUAT_CT_HR_KB_NHAP_CT] FOREIGN KEY ([HR_KB_NHAP_CTID]) REFERENCES [dbo].[HR_KB_NHAP_CT] ([HR_KB_NHAP_CTID])
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Adding foreign keys to [dbo].[CONT_KB_SOICHIEU_CT]'
GO
ALTER TABLE [dbo].[CONT_KB_SOICHIEU_CT] ADD
CONSTRAINT [FK_CONT_KB_SOICHIEU_CT_CONT_KB_SOICHIEU] FOREIGN KEY ([CONT_KB_SOICHIEUID]) REFERENCES [dbo].[CONT_KB_SOICHIEU] ([CONT_KB_SOICHIEUID])
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Adding foreign keys to [dbo].[HK_KB_NHAP_CT]'
GO
ALTER TABLE [dbo].[HK_KB_NHAP_CT] ADD
CONSTRAINT [FK_HK_KB_NHAP_CT_HK_KB_NHAP] FOREIGN KEY ([HK_KB_NHAPID]) REFERENCES [dbo].[HK_KB_NHAP] ([HK_KB_NHAPID])
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Adding foreign keys to [dbo].[HK_KB_XUAT]'
GO
ALTER TABLE [dbo].[HK_KB_XUAT] ADD
CONSTRAINT [FK_HK_KB_XUAT_SKHO] FOREIGN KEY ([MA_KHO]) REFERENCES [dbo].[SKHO] ([MA_KHO]),
CONSTRAINT [FK_HK_KB_XUAT_SLOAIHINH] FOREIGN KEY ([MA_LH]) REFERENCES [dbo].[SLOAIHINH] ([MA_LH]),
CONSTRAINT [FK_HK_KB_XUAT_SHAIQUAN] FOREIGN KEY ([MA_HQ]) REFERENCES [dbo].[SHAIQUAN] ([MA_HQ])
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Adding foreign keys to [dbo].[HK_VANDON_TRACUU_CT]'
GO
ALTER TABLE [dbo].[HK_VANDON_TRACUU_CT] ADD
CONSTRAINT [FK_HK_VANDON_TRACUU_CT_HK_VANDON_TRACUU] FOREIGN KEY ([HK_VANDON_TRACUUID]) REFERENCES [dbo].[HK_VANDON_TRACUU] ([HK_VANDON_TRACUUID]),
CONSTRAINT [FK_HK_VANDON_TRACUU_CT_SHAIQUAN] FOREIGN KEY ([MA_HQ]) REFERENCES [dbo].[SHAIQUAN] ([MA_HQ]),
CONSTRAINT [FK_HK_VANDON_TRACUU_CT_SHAIQUAN1] FOREIGN KEY ([MA_HQ_GIAM_SAT]) REFERENCES [dbo].[SHAIQUAN] ([MA_HQ])
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Adding foreign keys to [dbo].[HK_TOKHAI_TRACUU_CT]'
GO
ALTER TABLE [dbo].[HK_TOKHAI_TRACUU_CT] ADD
CONSTRAINT [FK_HK_TOKHAI_TRACUU_CT_HK_TOKHAI_TRACUU] FOREIGN KEY ([HK_TOKHAI_TRACUUID]) REFERENCES [dbo].[HK_TOKHAI_TRACUU] ([HK_TOKHAI_TRACUUID])
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Adding foreign keys to [dbo].[HK_KB_SUA]'
GO
ALTER TABLE [dbo].[HK_KB_SUA] ADD
CONSTRAINT [FK_HK_KB_SUA_HK_KB_NHAP] FOREIGN KEY ([HK_KB_NHAPID]) REFERENCES [dbo].[HK_KB_NHAP] ([HK_KB_NHAPID]),
CONSTRAINT [FK_HK_KB_SUA_SKHO] FOREIGN KEY ([MA_KHO]) REFERENCES [dbo].[SKHO] ([MA_KHO])
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Adding foreign keys to [dbo].[HK_VANDON_TRACUU]'
GO
ALTER TABLE [dbo].[HK_VANDON_TRACUU] ADD
CONSTRAINT [FK_HK_VANDON_TRACUU_SKHO] FOREIGN KEY ([MA_KHO]) REFERENCES [dbo].[SKHO] ([MA_KHO])
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
IF EXISTS (SELECT * FROM #tmpErrors) ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT>0 BEGIN
--Cập nhật phiên bản csdl
UPDATE SYSAPP SET GIA_TRI = '10' WHERE DATA_FIELD = 'DBVERSION'
PRINT 'The database updated succeeded'
COMMIT TRANSACTION
END
ELSE PRINT 'The database update failed'
GO
DROP TABLE #tmpErrors
GO
