/*
Script created by SQL Compare from Red Gate Software Ltd at 7/13/2017 10:34:33 AM
Run this script on PC01\SQL2008.ECUS5_CANG_PH to make it the same as PC01\SQL2008.ECUS5_CANG_DEV
Please back up your database before running this script
*/
SET NUMERIC_ROUNDABORT OFF
GO
SET ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, ARITHABORT, QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
IF EXISTS (SELECT * FROM tempdb..sysobjects WHERE id=OBJECT_ID('tempdb..#tmpErrors')) DROP TABLE #tmpErrors
GO
CREATE TABLE #tmpErrors (Error int)
GO
SET XACT_ABORT ON
GO
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
GO
BEGIN TRANSACTION
GO
PRINT N'Creating [dbo].[CONT_KB_HANGHOA]'
GO
CREATE TABLE [dbo].[CONT_KB_HANGHOA]
(
[CONT_KB_HANGHOAID] [numeric] (18, 0) NOT NULL IDENTITY(1, 1),
[MA_KHO] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SO_HIEU_PTVT] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HO_HIEU_TAU] [nvarchar] (35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SO_IMO] [nvarchar] (35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SO_CHUYEN] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGAY_TAU_DEN] [datetime] NULL,
[LOAI_HANG_HOA] [int] NULL,
[GHI_CHU] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TRANG_THAI] [int] NOT NULL CONSTRAINT [DF_CONT_KB_HANGHOA_TRANG_THAI] DEFAULT ((0)),
[SO_TN] [numeric] (18, 0) NULL,
[NGAY_TN] [datetime] NULL,
[MESSAGEID] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GUID] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGUOI_TAO] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGAY_TAO] [datetime] NULL,
[NGUOI_SUA] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGAY_SUA] [datetime] NULL
)

GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Creating primary key [PK_CONT_KB_HANGHOA] on [dbo].[CONT_KB_HANGHOA]'
GO
ALTER TABLE [dbo].[CONT_KB_HANGHOA] ADD CONSTRAINT [PK_CONT_KB_HANGHOA] PRIMARY KEY CLUSTERED  ([CONT_KB_HANGHOAID])
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Creating [dbo].[CONT_KB_HANGHOA_CT]'
GO
CREATE TABLE [dbo].[CONT_KB_HANGHOA_CT]
(
[CONT_KB_HANGHOA_CTID] [numeric] (18, 0) NOT NULL IDENTITY(1, 1),
[CONT_KB_HANGHOAID] [numeric] (18, 0) NULL,
[SO_HIEU_PTVT] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HO_HIEU_TAU] [nvarchar] (35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SO_IMO] [nvarchar] (35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SO_CHUYEN] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGAY_TAU_DEN] [datetime] NULL,
[SO_SEAL] [nvarchar] (35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SO_CONTAINER] [nvarchar] (35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TINH_TRANG] [int] NULL,
[GUID] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)

GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Creating primary key [PK_CONT_KB_HANGHOA_CT] on [dbo].[CONT_KB_HANGHOA_CT]'
GO
ALTER TABLE [dbo].[CONT_KB_HANGHOA_CT] ADD CONSTRAINT [PK_CONT_KB_HANGHOA_CT] PRIMARY KEY CLUSTERED  ([CONT_KB_HANGHOA_CTID])
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Creating [dbo].[CONT_KB_HANGHOA_CT_VANDON]'
GO
CREATE TABLE [dbo].[CONT_KB_HANGHOA_CT_VANDON]
(
[CONT_KB_HANGHOA_CT_VANDONID] [numeric] (18, 0) NOT NULL IDENTITY(1, 1),
[CONT_KB_HANGHOA_CTID] [numeric] (18, 0) NOT NULL,
[CONT_KB_HANGHOAID] [numeric] (18, 0) NOT NULL,
[SO_VAN_DON] [nvarchar] (35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DINH_DANH_HANG_HOA] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)

GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Creating primary key [PK_CONT_KB_HANGHOA_CT_VANDON] on [dbo].[CONT_KB_HANGHOA_CT_VANDON]'
GO
ALTER TABLE [dbo].[CONT_KB_HANGHOA_CT_VANDON] ADD CONSTRAINT [PK_CONT_KB_HANGHOA_CT_VANDON] PRIMARY KEY CLUSTERED  ([CONT_KB_HANGHOA_CT_VANDONID])
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Adding foreign keys to [dbo].[CONT_KB_HANGHOA_CT]'
GO
ALTER TABLE [dbo].[CONT_KB_HANGHOA_CT] ADD
CONSTRAINT [FK_CONT_KB_HANGHOA_CT_CONT_KB_HANGHOA] FOREIGN KEY ([CONT_KB_HANGHOAID]) REFERENCES [dbo].[CONT_KB_HANGHOA] ([CONT_KB_HANGHOAID])
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Adding foreign keys to [dbo].[CONT_KB_HANGHOA_CT_VANDON]'
GO
ALTER TABLE [dbo].[CONT_KB_HANGHOA_CT_VANDON] ADD
CONSTRAINT [FK_CONT_KB_HANGHOA_CT_VANDON_CONT_KB_HANGHOA] FOREIGN KEY ([CONT_KB_HANGHOAID]) REFERENCES [dbo].[CONT_KB_HANGHOA] ([CONT_KB_HANGHOAID]),
CONSTRAINT [FK_CONT_KB_HANGHOA_CT_VANDON_CONT_KB_HANGHOA_CT] FOREIGN KEY ([CONT_KB_HANGHOA_CTID]) REFERENCES [dbo].[CONT_KB_HANGHOA_CT] ([CONT_KB_HANGHOA_CTID])
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Adding foreign keys to [dbo].[CONT_KB_HANGHOA]'
GO
ALTER TABLE [dbo].[CONT_KB_HANGHOA] ADD
CONSTRAINT [FK_CONT_KB_HANGHOA_SKHO] FOREIGN KEY ([MA_KHO]) REFERENCES [dbo].[SKHO] ([MA_KHO])
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
IF EXISTS (SELECT * FROM #tmpErrors) ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT>0 BEGIN
--Cập nhật phiên bản csdl
UPDATE SYSAPP SET GIA_TRI = '7' WHERE DATA_FIELD = 'DBVERSION'
PRINT 'The database updated succeeded'
COMMIT TRANSACTION
END
ELSE PRINT 'The database update failed'
GO
DROP TABLE #tmpErrors
GO
