/*
Script created by SQL Compare from Red Gate Software Ltd at 5/18/2017 10:44:32 AM
Run this script on pc01\SQL2008.ECUS5_CANG_PH to make it the same as pc01\SQL2008.ECUS5_CANG_DEV
Please back up your database before running this script
*/
SET NUMERIC_ROUNDABORT OFF
GO
SET ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, ARITHABORT, QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
IF EXISTS (SELECT * FROM tempdb..sysobjects WHERE id=OBJECT_ID('tempdb..#tmpErrors')) DROP TABLE #tmpErrors
GO
CREATE TABLE #tmpErrors (Error int)
GO
SET XACT_ABORT ON
GO
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
GO
BEGIN TRANSACTION
GO
PRINT N'Altering [dbo].[DMESSAGEID]'
GO
ALTER TABLE [dbo].[DMESSAGEID] ALTER COLUMN [LOAI_CT] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL

GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Altering [dbo].[DLOGINFO]'
GO
ALTER TABLE [dbo].[DLOGINFO] ADD
[FUNCTION_CT_HT] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Altering [dbo].[CONT_KB_CONTAINER_CT]'
GO
ALTER TABLE [dbo].[CONT_KB_CONTAINER_CT] ALTER COLUMN [IS_DU_DK] [bit] NOT NULL

GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Adding constraints to [dbo].[CONT_KB_CONTAINER_CT]'
GO
ALTER TABLE [dbo].[CONT_KB_CONTAINER_CT] ADD CONSTRAINT [DF_CONT_KB_CONTAINER_CT_IS_DU_DK] DEFAULT ((0)) FOR [IS_DU_DK]
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
IF EXISTS (SELECT * FROM #tmpErrors) ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT>0 BEGIN
--Cập nhật phiên bản csdl
UPDATE SYSAPP SET GIA_TRI = '2' WHERE DATA_FIELD = 'DBVERSION'
PRINT 'The database updated succeeded'
COMMIT TRANSACTION
END
ELSE PRINT 'The database update failed'
GO
DROP TABLE #tmpErrors
GO
