/*
Script created by SQL Compare from Red Gate Software Ltd at 10/04/2017 8:29:54 AM
Run this script on PC01\SQL2008.ECUS5_CANG_PH to make it the same as PC01\SQL2008.ECUS5_CANG_DEV
Please back up your database before running this script
*/
SET NUMERIC_ROUNDABORT OFF
GO
SET ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, ARITHABORT, QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
IF EXISTS (SELECT * FROM tempdb..sysobjects WHERE id=OBJECT_ID('tempdb..#tmpErrors')) DROP TABLE #tmpErrors
GO
CREATE TABLE #tmpErrors (Error int)
GO
SET XACT_ABORT ON
GO
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
GO
BEGIN TRANSACTION
GO
PRINT N'Creating [dbo].[HR_KB_THAYDOI]'
GO
CREATE TABLE [dbo].[HR_KB_THAYDOI]
(
[HR_KB_THAYDOIID] [numeric] (18, 0) NOT NULL IDENTITY(1, 1),
[MA_KHO] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGAY_KB] [datetime] NULL,
[GHI_CHU] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[_XORN_CU] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[_XORN_MOI] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HR_KB_NHAPID] [numeric] (18, 0) NULL,
[SO_HIEU_PTVT] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SO_CHUYEN] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGAY_TAU_DEN] [datetime] NULL,
[TRANG_THAI] [int] NOT NULL CONSTRAINT [DF_HR_KB_THAYDOI_TRANG_THAI] DEFAULT ((0)),
[SO_TN] [numeric] (18, 0) NULL,
[NGAY_TN] [datetime] NULL,
[MESSAGEID] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GUID] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGUOI_TAO] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGAY_TAO] [datetime] NULL,
[NGUOI_SUA] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGAY_SUA] [datetime] NULL
)

GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Creating primary key [PK_HR_KB_THAYDOI] on [dbo].[HR_KB_THAYDOI]'
GO
ALTER TABLE [dbo].[HR_KB_THAYDOI] ADD CONSTRAINT [PK_HR_KB_THAYDOI] PRIMARY KEY CLUSTERED  ([HR_KB_THAYDOIID])
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Creating [dbo].[HR_KB_THAYDOI_CT]'
GO
CREATE TABLE [dbo].[HR_KB_THAYDOI_CT]
(
[HR_KB_THAYDOI_CTID] [numeric] (18, 0) NOT NULL IDENTITY(1, 1),
[HR_KB_THAYDOIID] [numeric] (18, 0) NULL,
[HR_KB_NHAP_CTID] [numeric] (18, 0) NULL,
[SO_VAN_DON] [nvarchar] (35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DINH_DANH_HANG_HOA] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GHI_CHU] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)

GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Creating primary key [PK_HR_KB_THAYDOI_CT] on [dbo].[HR_KB_THAYDOI_CT]'
GO
ALTER TABLE [dbo].[HR_KB_THAYDOI_CT] ADD CONSTRAINT [PK_HR_KB_THAYDOI_CT] PRIMARY KEY CLUSTERED  ([HR_KB_THAYDOI_CTID])
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Altering [dbo].[HR_KB_NHAP_CT]'
GO
ALTER TABLE [dbo].[HR_KB_NHAP_CT] ADD
[GHI_CHU_HT] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Adding foreign keys to [dbo].[HR_KB_THAYDOI_CT]'
GO
ALTER TABLE [dbo].[HR_KB_THAYDOI_CT] ADD
CONSTRAINT [FK_HR_KB_THAYDOI_CT_HR_KB_THAYDOI] FOREIGN KEY ([HR_KB_THAYDOIID]) REFERENCES [dbo].[HR_KB_THAYDOI] ([HR_KB_THAYDOIID]),
CONSTRAINT [FK_HR_KB_THAYDOI_CT_HR_KB_NHAP_CT] FOREIGN KEY ([HR_KB_NHAP_CTID]) REFERENCES [dbo].[HR_KB_NHAP_CT] ([HR_KB_NHAP_CTID])
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Adding foreign keys to [dbo].[HR_KB_THAYDOI]'
GO
ALTER TABLE [dbo].[HR_KB_THAYDOI] ADD
CONSTRAINT [FK_HR_KB_THAYDOI_SKHO] FOREIGN KEY ([MA_KHO]) REFERENCES [dbo].[SKHO] ([MA_KHO]),
CONSTRAINT [FK_HR_KB_THAYDOI_HR_KB_NHAP] FOREIGN KEY ([HR_KB_NHAPID]) REFERENCES [dbo].[HR_KB_NHAP] ([HR_KB_NHAPID])
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
IF EXISTS (SELECT * FROM #tmpErrors) ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT>0 BEGIN
--Cập nhật phiên bản CSDL
UPDATE SYSAPP SET GIA_TRI = '15' WHERE DATA_FIELD = 'DBVERSION'
PRINT 'The database updated succeeded'
COMMIT TRANSACTION
END
ELSE PRINT 'The database update failed'
GO
DROP TABLE #tmpErrors
GO
