/*
Script created by SQL Compare from Red Gate Software Ltd at 7/12/2017 11:29:11 AM
Run this script on PC01\SQL2008.ECUS5_CANG_PH to make it the same as PC01\SQL2008.ECUS5_CANG_DEV
Please back up your database before running this script
*/
SET NUMERIC_ROUNDABORT OFF
GO
SET ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, ARITHABORT, QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
IF EXISTS (SELECT * FROM tempdb..sysobjects WHERE id=OBJECT_ID('tempdb..#tmpErrors')) DROP TABLE #tmpErrors
GO
CREATE TABLE #tmpErrors (Error int)
GO
SET XACT_ABORT ON
GO
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
GO
BEGIN TRANSACTION
GO
PRINT N'Dropping foreign keys from [dbo].[CONT_KB_CONTAINER_OUT]'
GO
ALTER TABLE [dbo].[CONT_KB_CONTAINER_OUT] DROP
CONSTRAINT [FK_CONT_KB_CONTAINER_OUT_CONT_KB_CONTAINER]
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Dropping constraints from [dbo].[CONT_KB_CONTAINER_OUT]'
GO
ALTER TABLE [dbo].[CONT_KB_CONTAINER_OUT] DROP CONSTRAINT [DF_CONT_KB_CONTAINER_OUT_IS_CHUNGTU]
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Altering [dbo].[SKHO]'
GO
ALTER TABLE [dbo].[SKHO] ADD
[LOGO_DN] [ntext] COLLATE SQL_Latin1_General_CP1_CI_AS NULL
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Creating [dbo].[CONT_KB_CONTAINER_OUT_465_CT]'
GO
CREATE TABLE [dbo].[CONT_KB_CONTAINER_OUT_465_CT]
(
[CONT_KB_CONTAINER_OUT_465_CTID] [numeric] (18, 0) NOT NULL IDENTITY(1, 1),
[CONT_KB_CONTAINER_OUT_465ID] [numeric] (18, 0) NOT NULL,
[CONT_KB_CONTAINER_CTID] [numeric] (18, 0) NULL,
[SO_CONTAINER] [nvarchar] (35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SO_VAN_DON] [nvarchar] (35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DINH_DANH_HANG_HOA] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SO_SEAL] [nvarchar] (35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SO_HIEU_PTVT] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SO_CHUYEN] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGAY_TAU_DEN] [datetime] NULL,
[KIEU_PTVT] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BIEN_SO_XE] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CONTAINER_NHIEU_TO_KHAI] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SO_BBBG] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGAY_BBBG] [datetime] NULL,
[NGAY_RA_KHO] [datetime] NULL,
[GHI_CHU] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MA_HINH_THUC] [int] NULL,
[TINH_TRANG] [int] NULL
)

GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Creating primary key [PK_CONT_KB_CONTAINER_OUT_465_CT] on [dbo].[CONT_KB_CONTAINER_OUT_465_CT]'
GO
ALTER TABLE [dbo].[CONT_KB_CONTAINER_OUT_465_CT] ADD CONSTRAINT [PK_CONT_KB_CONTAINER_OUT_465_CT] PRIMARY KEY CLUSTERED  ([CONT_KB_CONTAINER_OUT_465_CTID])
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Altering [dbo].[CONT_KB_CONTAINER_OUT_CT]'
GO
ALTER TABLE [dbo].[CONT_KB_CONTAINER_OUT_CT] ADD
[BIEN_SO_XE] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Altering [dbo].[CONT_KB_CONTAINER_TT_CT]'
GO
ALTER TABLE [dbo].[CONT_KB_CONTAINER_TT_CT] ADD
[CONT_KB_CONTAINER_CTID] [numeric] (18, 0) NULL
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
ALTER TABLE [dbo].[CONT_KB_CONTAINER_TT_CT] ALTER COLUMN [SO_LUONG] [float] NULL

GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Creating [dbo].[CONT_KB_CONTAINER_TT_CT_X]'
GO
CREATE TABLE [dbo].[CONT_KB_CONTAINER_TT_CT_X]
(
[CONT_KB_CONTAINER_TT_CT_XID] [numeric] (18, 0) NOT NULL IDENTITY(1, 1),
[CONT_KB_CONTAINER_TTID] [numeric] (18, 0) NOT NULL,
[SOTK] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MA_HQ] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MA_LH] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGAY_DK] [date] NULL,
[GHI_CHU] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)

GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Creating primary key [PK_CONT_KB_CONTAINER_TT_CT_X] on [dbo].[CONT_KB_CONTAINER_TT_CT_X]'
GO
ALTER TABLE [dbo].[CONT_KB_CONTAINER_TT_CT_X] ADD CONSTRAINT [PK_CONT_KB_CONTAINER_TT_CT_X] PRIMARY KEY CLUSTERED  ([CONT_KB_CONTAINER_TT_CT_XID])
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Creating [dbo].[CONT_KB_SODO]'
GO
CREATE TABLE [dbo].[CONT_KB_SODO]
(
[CONT_KB_SODOID] [numeric] (18, 0) NOT NULL IDENTITY(1, 1),
[MA_KHO] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TEN_FILE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DUNG_LUONG] [float] NULL,
[NOI_DUNG] [ntext] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TRANG_THAI] [int] NOT NULL CONSTRAINT [DF_CONT_KB_SODO_TRANG_THAI] DEFAULT ((0)),
[SO_TN] [numeric] (18, 0) NULL,
[NGAY_TN] [datetime] NULL,
[MESSAGEID] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGUOI_TAO] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGAY_TAO] [datetime] NULL,
[NGUOI_SUA] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGAY_SUA] [datetime] NULL
)

GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Creating primary key [PK_CONT_KB_SODO] on [dbo].[CONT_KB_SODO]'
GO
ALTER TABLE [dbo].[CONT_KB_SODO] ADD CONSTRAINT [PK_CONT_KB_SODO] PRIMARY KEY CLUSTERED  ([CONT_KB_SODOID])
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Creating [dbo].[CONT_KB_CONTAINER_CT_VANDON]'
GO
CREATE TABLE [dbo].[CONT_KB_CONTAINER_CT_VANDON]
(
[CONT_KB_CONTAINER_CT_VANDONID] [numeric] (18, 0) NOT NULL IDENTITY(1, 1),
[CONT_KB_CONTAINER_CTID] [numeric] (18, 0) NOT NULL,
[SO_VAN_DON] [nvarchar] (35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DINH_DANH_HANG_HOA] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GHI_CHU] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)

GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Creating primary key [PK_CONT_KB_CONTAINER_CT_VANDON] on [dbo].[CONT_KB_CONTAINER_CT_VANDON]'
GO
ALTER TABLE [dbo].[CONT_KB_CONTAINER_CT_VANDON] ADD CONSTRAINT [PK_CONT_KB_CONTAINER_CT_VANDON] PRIMARY KEY CLUSTERED  ([CONT_KB_CONTAINER_CT_VANDONID])
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Altering [dbo].[CONT_KB_CONTAINER_TT]'
GO
ALTER TABLE [dbo].[CONT_KB_CONTAINER_TT] ADD
[MO_TA_HANG] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Creating [dbo].[CONT_KB_CONTAINER_OUT_465]'
GO
CREATE TABLE [dbo].[CONT_KB_CONTAINER_OUT_465]
(
[CONT_KB_CONTAINER_OUT_465ID] [numeric] (18, 0) NOT NULL IDENTITY(1, 1),
[MA_KHO] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[_XORN] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGAY_KB] [datetime] NULL,
[GHI_CHU] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TRANG_THAI] [int] NOT NULL CONSTRAINT [DF_CONT_KB_CONTAINER_OUT_465_TRANG_THAI] DEFAULT ((0)),
[SO_TN] [numeric] (18, 0) NULL,
[NGAY_TN] [datetime] NULL,
[MESSAGEID] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GUID] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGUOI_TAO] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGAY_TAO] [datetime] NULL,
[NGUOI_SUA] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGAY_SUA] [datetime] NULL
)

GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Creating primary key [PK_CONT_KB_CONTAINER_OUT_465] on [dbo].[CONT_KB_CONTAINER_OUT_465]'
GO
ALTER TABLE [dbo].[CONT_KB_CONTAINER_OUT_465] ADD CONSTRAINT [PK_CONT_KB_CONTAINER_OUT_465] PRIMARY KEY CLUSTERED  ([CONT_KB_CONTAINER_OUT_465ID])
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Altering [dbo].[CONT_KB_CONTAINER_OUT]'
GO
ALTER TABLE [dbo].[CONT_KB_CONTAINER_OUT] DROP
COLUMN [CONT_KB_CONTAINERID],
COLUMN [IS_CHUNGTU]
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Altering [dbo].[CONT_KB_CONTAINER_CT]'
GO
ALTER TABLE [dbo].[CONT_KB_CONTAINER_CT] ADD
[SO_XUAT_KHAU] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SO_SEAL] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GUID] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
ALTER TABLE [dbo].[CONT_KB_CONTAINER_CT] DROP
COLUMN [TINH_TRANG_HT]
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Adding foreign keys to [dbo].[CONT_KB_CONTAINER_CT_VANDON]'
GO
ALTER TABLE [dbo].[CONT_KB_CONTAINER_CT_VANDON] ADD
CONSTRAINT [FK_CONT_KB_CONTAINER_CT_VANDON_CONT_KB_CONTAINER_CT] FOREIGN KEY ([CONT_KB_CONTAINER_CTID]) REFERENCES [dbo].[CONT_KB_CONTAINER_CT] ([CONT_KB_CONTAINER_CTID])
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Adding foreign keys to [dbo].[CONT_KB_CONTAINER_OUT_465_CT]'
GO
ALTER TABLE [dbo].[CONT_KB_CONTAINER_OUT_465_CT] ADD
CONSTRAINT [FK_CONT_KB_CONTAINER_OUT_465_CT_CONT_KB_CONTAINER_OUT_465] FOREIGN KEY ([CONT_KB_CONTAINER_OUT_465ID]) REFERENCES [dbo].[CONT_KB_CONTAINER_OUT_465] ([CONT_KB_CONTAINER_OUT_465ID]),
CONSTRAINT [FK_CONT_KB_CONTAINER_OUT_465_CT_CONT_KB_CONTAINER_CT] FOREIGN KEY ([CONT_KB_CONTAINER_CTID]) REFERENCES [dbo].[CONT_KB_CONTAINER_CT] ([CONT_KB_CONTAINER_CTID])
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Adding foreign keys to [dbo].[CONT_KB_CONTAINER_OUT_465]'
GO
ALTER TABLE [dbo].[CONT_KB_CONTAINER_OUT_465] ADD
CONSTRAINT [FK_CONT_KB_CONTAINER_OUT_465_SKHO] FOREIGN KEY ([MA_KHO]) REFERENCES [dbo].[SKHO] ([MA_KHO])
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Adding foreign keys to [dbo].[CONT_KB_CONTAINER_TT_CT]'
GO
ALTER TABLE [dbo].[CONT_KB_CONTAINER_TT_CT] ADD
CONSTRAINT [FK_CONT_KB_CONTAINER_TT_CT_CONT_KB_CONTAINER_CT] FOREIGN KEY ([CONT_KB_CONTAINER_CTID]) REFERENCES [dbo].[CONT_KB_CONTAINER_CT] ([CONT_KB_CONTAINER_CTID])
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Adding foreign keys to [dbo].[CONT_KB_CONTAINER_TT_CT_X]'
GO
ALTER TABLE [dbo].[CONT_KB_CONTAINER_TT_CT_X] ADD
CONSTRAINT [FK_CONT_KB_CONTAINER_TT_CT_X_CONT_KB_CONTAINER_TT] FOREIGN KEY ([CONT_KB_CONTAINER_TTID]) REFERENCES [dbo].[CONT_KB_CONTAINER_TT] ([CONT_KB_CONTAINER_TTID])
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Adding foreign keys to [dbo].[CONT_KB_SODO]'
GO
ALTER TABLE [dbo].[CONT_KB_SODO] ADD
CONSTRAINT [FK_CONT_KB_SODO_SKHO] FOREIGN KEY ([MA_KHO]) REFERENCES [dbo].[SKHO] ([MA_KHO])
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
IF EXISTS (SELECT * FROM #tmpErrors) ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT>0 BEGIN
--Cập nhật phiên bản csdl
UPDATE SYSAPP SET GIA_TRI = '5' WHERE DATA_FIELD = 'DBVERSION'
PRINT 'The database updated succeeded'
COMMIT TRANSACTION
END
ELSE PRINT 'The database update failed'
GO
DROP TABLE #tmpErrors
GO
