/*
Script created by SQL Compare from Red Gate Software Ltd at 09/29/2017 2:23:55 PM
Run this script on pc01\sql2008.ECUS5_CANG_PH to make it the same as pc01\sql2008.ECUS5_CANG_DEV
Please back up your database before running this script
*/
SET NUMERIC_ROUNDABORT OFF
GO
SET ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, ARITHABORT, QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
IF EXISTS (SELECT * FROM tempdb..sysobjects WHERE id=OBJECT_ID('tempdb..#tmpErrors')) DROP TABLE #tmpErrors
GO
CREATE TABLE #tmpErrors (Error int)
GO
SET XACT_ABORT ON
GO
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
GO
BEGIN TRANSACTION
GO
PRINT N'Creating [dbo].[CONT_TRACUU_363_CT]'
GO
CREATE TABLE [dbo].[CONT_TRACUU_363_CT]
(
[CONT_TRACUU_363_CTID] [numeric] (18, 0) NOT NULL IDENTITY(1, 1),
[CONT_TRACUU_363ID] [numeric] (18, 0) NOT NULL,
[SO_VAN_DON] [nvarchar] (35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DINH_DANH_HANG_HOA] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)

GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Creating primary key [PK_CONT_TRACUU_363_CT] on [dbo].[CONT_TRACUU_363_CT]'
GO
ALTER TABLE [dbo].[CONT_TRACUU_363_CT] ADD CONSTRAINT [PK_CONT_TRACUU_363_CT] PRIMARY KEY CLUSTERED  ([CONT_TRACUU_363_CTID])
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Creating [dbo].[CONT_TRACUU_363]'
GO
CREATE TABLE [dbo].[CONT_TRACUU_363]
(
[CONT_TRACUU_363ID] [numeric] (18, 0) NOT NULL IDENTITY(1, 1),
[MA_KHO] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[_XORN] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SO_HIEU_PTVT] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SO_CHUYEN] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGAY_TAU_DEN] [datetime] NULL,
[SO_CONTAINER] [nvarchar] (35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SO_SEAL] [nvarchar] (35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TINH_TRANG] [int] NULL,
[VI_TRI_HANG] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MO_TA_HANG] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SOTK] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGAY_DK] [datetime] NULL,
[MA_LH] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MA_HQ] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MA_HQ_GIAM_SAT] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PHAN_LUONG] [nchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MA_TTTK] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MA_DV] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TEN_DV] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[THOI_GIAN_KET_XUAT] [datetime] NULL,
[TRANG_THAI] [int] NOT NULL CONSTRAINT [DF_CONT_TRACUU_363_TRANG_THAI] DEFAULT ((0)),
[GUID] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SO_TN] [bigint] NULL,
[NGAY_TN] [datetime] NULL,
[MESSAGEID] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGUOI_TAO] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGAY_TAO] [datetime] NULL,
[NGUOI_SUA] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGAY_SUA] [datetime] NULL
)

GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Creating primary key [PK_CONT_TRACUU_363] on [dbo].[CONT_TRACUU_363]'
GO
ALTER TABLE [dbo].[CONT_TRACUU_363] ADD CONSTRAINT [PK_CONT_TRACUU_363] PRIMARY KEY CLUSTERED  ([CONT_TRACUU_363ID])
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Altering [dbo].[KB_HH_CHUYEN_CANG_CT]'
GO
IF NOT EXISTS (SELECT TOP 1 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KB_HH_CHUYEN_CANG_CT' AND COLUMN_NAME = 'NGUOI_TAO')
BEGIN
	ALTER TABLE [dbo].[KB_HH_CHUYEN_CANG_CT] ADD
	[NGUOI_TAO] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[NGAY_TAO] [datetime] NULL,
	[NGUOI_SUA] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[NGAY_SUA] [datetime] NULL
END
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Adding foreign keys to [dbo].[CONT_TRACUU_363_CT]'
GO
ALTER TABLE [dbo].[CONT_TRACUU_363_CT] ADD
CONSTRAINT [FK_CONT_TRACUU_363_CT_CONT_TRACUU_363] FOREIGN KEY ([CONT_TRACUU_363ID]) REFERENCES [dbo].[CONT_TRACUU_363] ([CONT_TRACUU_363ID])
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
IF EXISTS (SELECT * FROM #tmpErrors) ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT>0 BEGIN
--Cập nhật phiên bản csdl
UPDATE SYSAPP SET GIA_TRI = '14' WHERE DATA_FIELD = 'DBVERSION'
PRINT 'The database updated succeeded'
COMMIT TRANSACTION
END
ELSE PRINT 'The database update failed'
GO
DROP TABLE #tmpErrors
GO
