/*
Script created by SQL Compare from Red Gate Software Ltd at 10/05/2017 5:16:33 PM
Run this script on PC01\SQL2008.ECUS5_CANG_PH to make it the same as PC01\SQL2008.ECUS5_CANG_DEV
Please back up your database before running this script
*/
SET NUMERIC_ROUNDABORT OFF
GO
SET ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, ARITHABORT, QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
IF EXISTS (SELECT * FROM tempdb..sysobjects WHERE id=OBJECT_ID('tempdb..#tmpErrors')) DROP TABLE #tmpErrors
GO
CREATE TABLE #tmpErrors (Error int)
GO
SET XACT_ABORT ON
GO
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
GO
BEGIN TRANSACTION
GO
PRINT N'Creating [dbo].[DCONGKY]'
GO
CREATE TABLE [dbo].[DCONGKY]
(
[DCONGKYID] [numeric] (18, 0) NOT NULL IDENTITY(1, 1),
[MA_NSD] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TEN_MAY] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGAY_GUI] [datetime] NULL,
[DU_LIEU] [ntext] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DU_LIEU_KY] [ntext] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TAP_TIN_CERT] [ntext] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TRANG_THAI] [int] NOT NULL CONSTRAINT [DF_DCONGKY_TRANG_THAI] DEFAULT ((0)),
[GUID] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)

GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Creating primary key [PK_DCONGKY] on [dbo].[DCONGKY]'
GO
ALTER TABLE [dbo].[DCONGKY] ADD CONSTRAINT [PK_DCONGKY] PRIMARY KEY CLUSTERED  ([DCONGKYID])
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Altering [dbo].[HK_KB_NHAP_CT]'
GO
ALTER TABLE [dbo].[HK_KB_NHAP_CT] ADD
[SO_LUONG_OUT] [int] NULL
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Altering [dbo].[HR_KB_NHAP_CT]'
GO
ALTER TABLE [dbo].[HR_KB_NHAP_CT] ADD
[SO_LUONG_OUT] [float] NULL
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
IF EXISTS (SELECT * FROM #tmpErrors) ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT>0 BEGIN
--Cập nhật phiên bản CSDL
UPDATE SYSAPP SET GIA_TRI = '17' WHERE DATA_FIELD = 'DBVERSION'
PRINT 'The database updated succeeded'
COMMIT TRANSACTION
END
ELSE PRINT 'The database update failed'
GO
DROP TABLE #tmpErrors
GO
