/*
Script created by SQL Compare from Red Gate Software Ltd at 7/13/2017 5:09:21 PM
Run this script on PC01\SQL2008.ECUS5_CANG_PH to make it the same as PC01\SQL2008.ECUS5_CANG_DEV
Please back up your database before running this script
*/
SET NUMERIC_ROUNDABORT OFF
GO
SET ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, ARITHABORT, QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
IF EXISTS (SELECT * FROM tempdb..sysobjects WHERE id=OBJECT_ID('tempdb..#tmpErrors')) DROP TABLE #tmpErrors
GO
CREATE TABLE #tmpErrors (Error int)
GO
SET XACT_ABORT ON
GO
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
GO
BEGIN TRANSACTION
GO
PRINT N'Creating [dbo].[KB_TAU_CT]'
GO
CREATE TABLE [dbo].[KB_TAU_CT]
(
[KB_TAU_CTID] [numeric] (18, 0) NOT NULL IDENTITY(1, 1),
[KB_TAUID] [numeric] (18, 0) NOT NULL,
[SO_HIEU_PTVT] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HO_HIEU_TAU] [nvarchar] (35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SO_IMO] [nvarchar] (35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGAY_TAU_DEN] [datetime] NULL,
[SO_CHUYEN] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)

GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Creating primary key [PK_KB_TAU_CT] on [dbo].[KB_TAU_CT]'
GO
ALTER TABLE [dbo].[KB_TAU_CT] ADD CONSTRAINT [PK_KB_TAU_CT] PRIMARY KEY CLUSTERED  ([KB_TAU_CTID])
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Creating [dbo].[KB_TAU]'
GO
CREATE TABLE [dbo].[KB_TAU]
(
[KB_TAUID] [numeric] (18, 0) NOT NULL IDENTITY(1, 1),
[MA_KHO] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGAY_BAT_DAU] [datetime] NULL,
[NGAY_KET_THUC] [datetime] NULL,
[LOAI] [int] NULL,
[GHI_CHU] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TRANG_THAI] [int] NOT NULL CONSTRAINT [DF_KB_TAU_TRANG_THAI] DEFAULT ((0)),
[GUID] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SO_TN] [numeric] (18, 0) NULL,
[NGAY_TN] [datetime] NULL,
[MESSAGEID] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGUOI_TAO] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGAY_TAO] [datetime] NULL,
[NGUOI_SUA] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGAY_SUA] [datetime] NULL
)

GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Creating primary key [PK_KB_TAU] on [dbo].[KB_TAU]'
GO
ALTER TABLE [dbo].[KB_TAU] ADD CONSTRAINT [PK_KB_TAU] PRIMARY KEY CLUSTERED  ([KB_TAUID])
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Adding foreign keys to [dbo].[KB_TAU_CT]'
GO
ALTER TABLE [dbo].[KB_TAU_CT] ADD
CONSTRAINT [FK_KB_TAU_CT_KB_TAU] FOREIGN KEY ([KB_TAUID]) REFERENCES [dbo].[KB_TAU] ([KB_TAUID])
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Adding foreign keys to [dbo].[KB_TAU]'
GO
ALTER TABLE [dbo].[KB_TAU] ADD
CONSTRAINT [FK_KB_TAU_SKHO] FOREIGN KEY ([MA_KHO]) REFERENCES [dbo].[SKHO] ([MA_KHO])
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
IF EXISTS (SELECT * FROM #tmpErrors) ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT>0 BEGIN
--Cập nhật phiên bản csdl
UPDATE SYSAPP SET GIA_TRI = '8' WHERE DATA_FIELD = 'DBVERSION'
PRINT 'The database updated succeeded'
COMMIT TRANSACTION
END
ELSE PRINT 'The database update failed'
GO
DROP TABLE #tmpErrors
GO
