/*
Script created by SQL Compare from Red Gate Software Ltd at 7/12/2017 9:26:48 PM
Run this script on PC01\SQL2008.ECUS5_CANG_PH to make it the same as PC01\SQL2008.ECUS5_CANG_DEV
Please back up your database before running this script
*/
SET NUMERIC_ROUNDABORT OFF
GO
SET ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, ARITHABORT, QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
IF EXISTS (SELECT * FROM tempdb..sysobjects WHERE id=OBJECT_ID('tempdb..#tmpErrors')) DROP TABLE #tmpErrors
GO
CREATE TABLE #tmpErrors (Error int)
GO
SET XACT_ABORT ON
GO
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
GO
BEGIN TRANSACTION
GO
PRINT N'Altering [dbo].[CONT_KB_CONTAINER]'
GO
ALTER TABLE [dbo].[CONT_KB_CONTAINER] ADD
[SO_TN_SUA] [numeric] (18, 0) NULL,
[NGAY_TN_SUA] [datetime] NULL
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Altering [dbo].[CONT_KB_CONTAINER_CT]'
GO
ALTER TABLE [dbo].[CONT_KB_CONTAINER_CT] ADD
[GHI_CHU_XUAT] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Creating [dbo].[CONT_KB_HUY]'
GO
CREATE TABLE [dbo].[CONT_KB_HUY]
(
[CONT_KB_HUYID] [numeric] (18, 0) NOT NULL IDENTITY(1, 1),
[_XORN] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MA_KHO] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CONT_KB_CONTAINER_CTID] [numeric] (18, 0) NOT NULL,
[NGAY_KB] [datetime] NULL,
[LY_DO_HUY] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GHI_CHU] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GUID] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SO_TN] [numeric] (18, 0) NULL,
[NGAY_TN] [datetime] NULL,
[MESSAGEID] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TRANG_THAI] [int] NOT NULL CONSTRAINT [DF_CONT_KB_HUY_TRANG_THAI] DEFAULT ((0)),
[NGUOI_TAO] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGAY_TAO] [datetime] NULL,
[NGUOI_SUA] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGAY_SUA] [datetime] NULL
)

GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Creating primary key [PK_CONT_KB_HUY] on [dbo].[CONT_KB_HUY]'
GO
ALTER TABLE [dbo].[CONT_KB_HUY] ADD CONSTRAINT [PK_CONT_KB_HUY] PRIMARY KEY CLUSTERED  ([CONT_KB_HUYID])
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Creating [dbo].[CONT_KB_SUA]'
GO
CREATE TABLE [dbo].[CONT_KB_SUA]
(
[CONT_KB_SUAID] [numeric] (18, 0) NOT NULL IDENTITY(1, 1),
[MA_KHO] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[_XORN] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGAY_KB] [datetime] NULL,
[GHI_CHU] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SO_HIEU_PTVT_CU] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SO_CHUYEN_CU] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGAY_TAU_DEN_CU] [datetime] NULL,
[NGAY_VAO_KHO_CU] [datetime] NULL,
[SO_HIEU_PTVT] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SO_CHUYEN] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGAY_TAU_DEN] [datetime] NULL,
[NGAY_VAO_KHO] [datetime] NULL,
[LY_DO_SUA] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CONT_KB_CONTAINERID] [numeric] (18, 0) NULL,
[GUID] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TRANG_THAI] [int] NOT NULL CONSTRAINT [DF_CONT_KB_SUA_TRANG_THAI] DEFAULT ((0)),
[SO_TN] [numeric] (18, 0) NULL,
[NGAY_TN] [datetime] NULL,
[MESSAGEID] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGUOI_TAO] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGAY_TAO] [datetime] NULL,
[NGUOI_SUA] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGAY_SUA] [datetime] NULL
)

GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Creating primary key [PK_CONT_KB_SUA] on [dbo].[CONT_KB_SUA]'
GO
ALTER TABLE [dbo].[CONT_KB_SUA] ADD CONSTRAINT [PK_CONT_KB_SUA] PRIMARY KEY CLUSTERED  ([CONT_KB_SUAID])
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Adding foreign keys to [dbo].[CONT_KB_HUY]'
GO
ALTER TABLE [dbo].[CONT_KB_HUY] ADD
CONSTRAINT [FK_CONT_KB_HUY_CONT_KB_CONTAINER_CT] FOREIGN KEY ([CONT_KB_CONTAINER_CTID]) REFERENCES [dbo].[CONT_KB_CONTAINER_CT] ([CONT_KB_CONTAINER_CTID])
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Adding foreign keys to [dbo].[CONT_KB_SUA]'
GO
ALTER TABLE [dbo].[CONT_KB_SUA] ADD
CONSTRAINT [FK_CONT_KB_SUA_SKHO] FOREIGN KEY ([MA_KHO]) REFERENCES [dbo].[SKHO] ([MA_KHO]),
CONSTRAINT [FK_CONT_KB_SUA_CONT_KB_CONTAINER] FOREIGN KEY ([CONT_KB_CONTAINERID]) REFERENCES [dbo].[CONT_KB_CONTAINER] ([CONT_KB_CONTAINERID])
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
IF EXISTS (SELECT * FROM #tmpErrors) ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT>0 BEGIN
--Cập nhật phiên bản csdl
UPDATE SYSAPP SET GIA_TRI = '6' WHERE DATA_FIELD = 'DBVERSION'
PRINT 'The database updated succeeded'
COMMIT TRANSACTION
END
ELSE PRINT 'The database update failed'
GO
DROP TABLE #tmpErrors
GO
