/*
Script created by SQL Compare from Red Gate Software Ltd at 09/28/2017 5:11:40 PM
Run this script on pc01\sql2008.ECUS5_CANG_PH to make it the same as pc01\sql2008.ECUS5_CANG_DEV
Please back up your database before running this script
*/
SET NUMERIC_ROUNDABORT OFF
GO
SET ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, ARITHABORT, QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
IF EXISTS (SELECT * FROM tempdb..sysobjects WHERE id=OBJECT_ID('tempdb..#tmpErrors')) DROP TABLE #tmpErrors
GO
CREATE TABLE #tmpErrors (Error int)
GO
SET XACT_ABORT ON
GO
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
GO
BEGIN TRANSACTION
GO
PRINT N'Altering [dbo].[CONT_KB_TKVC_CT_VANDON]'
GO
ALTER TABLE [dbo].[CONT_KB_TKVC_CT_VANDON] ADD
[CONT_KB_TKVCID] [numeric] (18, 0) NULL
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Creating [dbo].[CONT_KB_NIEMPHONG_CT]'
GO
CREATE TABLE [dbo].[CONT_KB_NIEMPHONG_CT]
(
[CONT_KB_NIEMPHONG_CTID] [numeric] (18, 0) NOT NULL IDENTITY(1, 1),
[CONT_KB_NIEMPHONGID] [numeric] (18, 0) NULL,
[CONT_KB_CONTAINER_CTID] [numeric] (18, 0) NULL,
[SO_CONTAINER] [nvarchar] (35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SO_HIEU_PTVT] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SO_CHUYEN] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGAY_TAU_DEN] [datetime] NULL,
[SO_SEAL] [nvarchar] (35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SO_SEAL_MOI] [nvarchar] (35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LOAI_THAY_DOI] [int] NULL,
[LY_DO] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)

GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Creating primary key [PK_CONT_KB_NIEMPHONG_CT] on [dbo].[CONT_KB_NIEMPHONG_CT]'
GO
ALTER TABLE [dbo].[CONT_KB_NIEMPHONG_CT] ADD CONSTRAINT [PK_CONT_KB_NIEMPHONG_CT] PRIMARY KEY CLUSTERED  ([CONT_KB_NIEMPHONG_CTID])
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Creating [dbo].[CONT_KB_NIEMPHONG]'
GO
CREATE TABLE [dbo].[CONT_KB_NIEMPHONG]
(
[CONT_KB_NIEMPHONGID] [numeric] (18, 0) NOT NULL IDENTITY(1, 1),
[MA_KHO] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[_XORN] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGAY_KB] [datetime] NULL,
[GHI_CHU] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TRANG_THAI] [int] NOT NULL CONSTRAINT [DF_CONT_KB_NIEMPHONG_TRANG_THAI] DEFAULT ((0)),
[GUID] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SO_TN] [numeric] (18, 0) NULL,
[NGAY_TN] [datetime] NULL,
[MESSAGEID] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGUOI_TAO] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGAY_TAO] [datetime] NULL,
[NGUOI_SUA] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGAY_SUA] [datetime] NULL
)

GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Creating primary key [PK_CONT_KB_NIEMPHONG] on [dbo].[CONT_KB_NIEMPHONG]'
GO
ALTER TABLE [dbo].[CONT_KB_NIEMPHONG] ADD CONSTRAINT [PK_CONT_KB_NIEMPHONG] PRIMARY KEY CLUSTERED  ([CONT_KB_NIEMPHONGID])
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Altering [dbo].[CONT_KB_CONTAINER_CT]'
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'CONT_KB_CONTAINER_CT' AND COLUMN_NAME = 'SOTK_XUAT')
BEGIN
	ALTER TABLE [dbo].[CONT_KB_CONTAINER_CT] ADD
	[SO_SEAL_CU] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SOTK_XUAT] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
END 
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Altering [dbo].[HR_KB_NHAP_CT]'
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'HR_KB_NHAP_CT' AND COLUMN_NAME = 'SOTK_XUAT')
BEGIN
	ALTER TABLE [dbo].[HR_KB_NHAP_CT] ADD
	[SOTK_XUAT] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
END
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Altering [dbo].[HK_KB_NHAP_CT]'
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'HK_KB_NHAP_CT' AND COLUMN_NAME = 'SOTK_XUAT')
BEGIN
	ALTER TABLE [dbo].[HK_KB_NHAP_CT] ADD
	[SOTK_XUAT] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
END
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Altering [dbo].[SYSCHUC_NANG]'
GO
ALTER TABLE [dbo].[SYSCHUC_NANG] ADD
[STT] [int] NULL
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Altering [dbo].[SYSTHAO_TAC]'
GO
ALTER TABLE [dbo].[SYSTHAO_TAC] ADD
[STT] [int] NULL
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Creating primary key [PK_SYSTHAO_TAC] on [dbo].[SYSTHAO_TAC]'
GO
ALTER TABLE [dbo].[SYSTHAO_TAC] ADD CONSTRAINT [PK_SYSTHAO_TAC] PRIMARY KEY CLUSTERED  ([SYSTHAO_TACID])
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Creating [dbo].[KB_HH_CHUYEN_CANG]'
GO
CREATE TABLE [dbo].[KB_HH_CHUYEN_CANG]
(
[KB_HH_CHUYEN_CANGID] [numeric] (18, 0) NOT NULL IDENTITY(1, 1),
[MA_KHO] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LOAI_HH] [int] NOT NULL,
[LOAI_YC] [int] NOT NULL,
[NGAY_KB] [datetime] NULL,
[GHI_CHU] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TRANG_THAI] [int] NOT NULL,
[GUID] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SO_TN] [numeric] (18, 0) NULL,
[NGAY_TN] [datetime] NULL,
[MESSAGEID] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGUOI_TAO] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGAY_TAO] [datetime] NULL,
[NGUOI_SUA] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGAY_SUA] [datetime] NULL
)

GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Creating primary key [PK_KB_HH_CHUYEN_CANG] on [dbo].[KB_HH_CHUYEN_CANG]'
GO
ALTER TABLE [dbo].[KB_HH_CHUYEN_CANG] ADD CONSTRAINT [PK_KB_HH_CHUYEN_CANG] PRIMARY KEY CLUSTERED  ([KB_HH_CHUYEN_CANGID])
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Creating [dbo].[KB_HH_CHUYEN_CANG_CT]'
GO
CREATE TABLE [dbo].[KB_HH_CHUYEN_CANG_CT]
(
[KB_HH_CHUYEN_CANG_CTID] [numeric] (18, 0) NOT NULL IDENTITY(1, 1),
[KB_HH_CHUYEN_CANGID] [numeric] (18, 0) NOT NULL,
[SO_VANDON] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGAY_VANDON] [datetime] NULL,
[MA_DIA_DIEM] [varchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SO_DINH_DANH] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SO_CONTAINER] [nvarchar] (35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SO_SEAL] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SO_HIEU_PTVT] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SO_CHUYEN] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGAY_DEN] [datetime] NULL,
[MO_TA] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GHI_CHU] [nvarchar] (300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GUID] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)

GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Creating primary key [PK_KB_HH_CHUYEN_CANG_CT] on [dbo].[KB_HH_CHUYEN_CANG_CT]'
GO
ALTER TABLE [dbo].[KB_HH_CHUYEN_CANG_CT] ADD CONSTRAINT [PK_KB_HH_CHUYEN_CANG_CT] PRIMARY KEY CLUSTERED  ([KB_HH_CHUYEN_CANG_CTID])
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Creating [dbo].[KB_HH_CHUYEN_CANG_CT_VANDON]'
GO
CREATE TABLE [dbo].[KB_HH_CHUYEN_CANG_CT_VANDON]
(
[KB_HH_CHUYEN_CANG_CT_VANDONID] [numeric] (18, 0) NOT NULL IDENTITY(1, 1),
[KB_HH_CHUYEN_CANG_CTID] [numeric] (18, 0) NOT NULL,
[KB_HH_CHUYEN_CANGID] [numeric] (18, 0) NOT NULL,
[SO_VANDON] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGAY_VANDON] [datetime] NULL,
[MA_DIA_DIEM] [varchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DINH_DANH_HANG_HOA] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)

GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Creating primary key [PK_KB_HH_CHUYEN_CANG_CT_VANDON] on [dbo].[KB_HH_CHUYEN_CANG_CT_VANDON]'
GO
ALTER TABLE [dbo].[KB_HH_CHUYEN_CANG_CT_VANDON] ADD CONSTRAINT [PK_KB_HH_CHUYEN_CANG_CT_VANDON] PRIMARY KEY CLUSTERED  ([KB_HH_CHUYEN_CANG_CT_VANDONID])
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Adding constraints to [dbo].[SYSTHAO_TAC]'
GO
ALTER TABLE [dbo].[SYSTHAO_TAC] ADD CONSTRAINT [UK_SYSTHAO_TAC] UNIQUE NONCLUSTERED  ([MA_CHUC_NANG], [MA_THAO_TAC])
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Adding foreign keys to [dbo].[CONT_KB_NIEMPHONG_CT]'
GO
ALTER TABLE [dbo].[CONT_KB_NIEMPHONG_CT] ADD
CONSTRAINT [FK_CONT_KB_NIEMPHONG_CT_CONT_KB_NIEMPHONG] FOREIGN KEY ([CONT_KB_NIEMPHONGID]) REFERENCES [dbo].[CONT_KB_NIEMPHONG] ([CONT_KB_NIEMPHONGID]),
CONSTRAINT [FK_CONT_KB_NIEMPHONG_CT_CONT_KB_CONTAINER_CT] FOREIGN KEY ([CONT_KB_CONTAINER_CTID]) REFERENCES [dbo].[CONT_KB_CONTAINER_CT] ([CONT_KB_CONTAINER_CTID])
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Adding foreign keys to [dbo].[CONT_KB_NIEMPHONG]'
GO
ALTER TABLE [dbo].[CONT_KB_NIEMPHONG] ADD
CONSTRAINT [FK_CONT_KB_NIEMPHONG_SKHO] FOREIGN KEY ([MA_KHO]) REFERENCES [dbo].[SKHO] ([MA_KHO])
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
PRINT N'Adding foreign keys to [dbo].[CONT_KB_TKVC_CT_VANDON]'
GO
ALTER TABLE [dbo].[CONT_KB_TKVC_CT_VANDON] ADD
CONSTRAINT [FK_CONT_KB_TKVC_CT_VANDON_CONT_KB_TKVC] FOREIGN KEY ([CONT_KB_TKVCID]) REFERENCES [dbo].[CONT_KB_TKVC] ([CONT_KB_TKVCID])
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
IF EXISTS (SELECT * FROM #tmpErrors) ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT>0 BEGIN
--Cập nhật phiên bản csdl
UPDATE SYSAPP SET GIA_TRI = '13' WHERE DATA_FIELD = 'DBVERSION'
PRINT 'The database updated succeeded'
COMMIT TRANSACTION
END
ELSE PRINT 'The database update failed'
GO
DROP TABLE #tmpErrors
GO
